redhat-developer/quarkus-ls

- quarkus.jdt/.mvn/wrapper/MavenWrapperDownloader.java
- quarkus.jdt/.mvn/wrapper/maven-wrapper.properties
- quarkus.jdt/mvnw
- quarkus.jdt/mvnw.cmd
- quarkus.ls/com.redhat.quarkus.ls/.mvn/wrapper/MavenWrapperDownloader.java
- quarkus.ls/com.redhat.quarkus.ls/.mvn/wrapper/maven-wrapper.properties
- quarkus.ls/com.redhat.quarkus.ls/mvnw
- quarkus.ls/com.redhat.quarkus.ls/mvnw.cmd
This PR is a part of the fix for #7 
The second part of this PR is [here](https://github.com/redhat-developer/vscode-quarkus/pull/10).
These files are needed for the build script run.
> Create maven wrapper files

- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/commons/ExtendedConfigDescriptionBuildItem.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/commons/ExtendedConfigDescriptionBuildItem.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java
Snippet choice support for enum and boolean.
See #1
> Snippet choice support for enum and boolean.

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java
> Completion fails on empty line.

- quarkus.jdt/com.redhat.quarkus.jdt.core/META-INF/MANIFEST.MF
- quarkus.jdt/com.redhat.quarkus.jdt.core/plugin.xml
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/commons/QuarkusProjectInfo.java
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/core/JDTQuarkusManager.java
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/internal/core/IClasspathChangedListener.java
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/internal/core/QuarkusActivator.java
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/internal/core/QuarkusClasspathListenerManager.java
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/internal/core/QuarkusConstants.java
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/internal/core/ls/QuarkusDelegateCommandHandler.java
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/internal/core/utils/JDTQuarkusUtils.java
- quarkus.jdt/com.redhat.quarkus.jdt.test/src/main/java/com/redhat/quarkus/jdt/internal/core/QuarkusClasspathListenerManagerTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/commons/QuarkusProjectInfo.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusLanguageServer.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusProjectInfoCache.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusProjectInfoProvider.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusTextDocumentService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/commons/TreeLineTracker.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/QuarkusCapabilityManager.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PositionUtils.java
Update Quarkus properties (from cache) when classpath changed
Fixes #10
> Update Quarkus properties (from cache) when classpath changed

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java
Removed spaces around equals sign and edited tests.
> Remove spacing around equals sign on completion

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java
> Remove double quote for map property completion

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/DocumentationUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/QuarkusPropertiesUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/commons/QuarkusProjectInfoTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesHoverTest.java
Need to escape asterisks in Completion item documentation titles
Fixes #66
> Need to escape asterisks in Completion item documentation titles

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusTextDocumentService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/PropertiesModel.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusHover.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusSymbolsProvider.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ClientCapabilitiesWrapper.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/QuarkusCapabilityManager.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ServerCapabilitiesConstants.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ServerCapabilitiesInitializer.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesSymbolsTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java
Support for `textDocument/documentSymbol`
Fixes #22
> Support for `textDocument/documentSymbol`

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusLanguageServer.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusTextDocumentService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusWorkspaceService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusHover.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusSymbolsProvider.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/AllQuarkusSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/InitializationOptionsSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/QuarkusGeneralClientSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/QuarkusSymbolSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/SharedSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/JSONUtility.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PositionUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesSymbolsTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/settings/SettingsTest.java
Support for `textDocument/documentSymbol`as tree
Fixes #72
> Support for `textDocument/documentSymbol`as tree

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusLanguageServer.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusTextDocumentService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/Node.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/PropertiesModel.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusDiagnostics.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusSymbolsProvider.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusValidator.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/ValidationType.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/QuarkusGeneralClientSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/QuarkusValidationSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/QuarkusValidationTypeSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/SharedSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesDiagnosticsTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/settings/SettingsTest.java
> Validate application.properties: unknown properties

- quarkus.jdt/com.redhat.quarkus.jdt.test/src/main/java/com/redhat/quarkus/jdt/internal/core/QuarkusPropertiesListenerManagerTest.java
Fix test with classpath changed
> Fix test with classpath changed

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/Property.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/PropertyKey.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusValidator.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesDiagnosticsTest.java
Duplicate property detection not useful when using profiles
See https://github.com/redhat-developer/vscode-quarkus/issues/87
> Duplicate property detection not useful when using profiles

- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/commons/EnumItem.java
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/commons/ExtendedConfigDescriptionBuildItem.java
- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/core/JDTQuarkusManager.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/commons/EnumItem.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/commons/ExtendedConfigDescriptionBuildItem.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/PropertyValue.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusHover.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/DocumentationUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesHoverTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/resources/com/redhat/quarkus/services/all-quarkus-properties.json
Freeze API for enumeration (String -> EnumItem)
Fixes #99
> Freeze API for enumeration (String -> EnumItem)

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusProjectInfoCache.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/QuarkusPropertiesUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/ls/QuarkusLanguageServerScopeChangedTest.java
Duplicate completion options for ConfigProperty
Fixes #101
> Duplicate completion options for ConfigProperty

- quarkus.ls/com.redhat.quarkus.ls/pom.xml
Updates lsp4j version to 0.8.1.
> Update lsp4j version to 0.8.1

- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesHoverTest.java
Fix profile tests on Windows OS.
> Fix profile tests on Windows OS.

- quarkus.ls/com.redhat.quarkus.ls/pom.xml
This allows deploying the quarkus ls to Nexus.
I have a Jenkins Job (quarkus-ls) that takes this branch and successfully deployed to Nexus.
As soon as this is merged, I will update so that it works from master.
Fixes #76
> Add Nexus repos

- quarkus.ls/com.redhat.quarkus.ls/pom.xml
> Produce source JAR for quarkus-ls

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/api/QuarkusPropertyDefinitionProvider.java
> Add method to QuarkusLanguageClientAPI is now defaulted

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/QuarkusValidationTypeSettings.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/AntPathMatcher.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PathMatcher.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/StringUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesDiagnosticsTest.java
Support glob pattern to exclude unknown validation
Fixes #79
> Support glob pattern to exclude unknown validation

- quarkus.jdt/com.redhat.quarkus.jdt.site/pom.xml
- quarkus.jdt/pom.xml
> Add rsync deployment to download.jboss.org

- quarkus.jdt/pom.xml
> Test timeout for quarkus.jdk is now a parameter

- quarkus.jdt/com.redhat.quarkus.jdt.core/META-INF/MANIFEST.MF
- quarkus.jdt/com.redhat.quarkus.jdt.core/pom.xml
- quarkus.jdt/com.redhat.quarkus.jdt.site/pom.xml
- quarkus.jdt/com.redhat.quarkus.jdt.test/META-INF/MANIFEST.MF
- quarkus.jdt/com.redhat.quarkus.jdt.test/pom.xml
- quarkus.jdt/pom.xml
- quarkus.ls/CHANGELOG.md
- quarkus.ls/com.redhat.quarkus.ls/pom.xml
> CHANGELOG for 0.0.3

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusTextDocumentService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/LevenshteinDistance.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCodeActions.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ClientCapabilitiesWrapper.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/QuarkusCapabilityManager.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ServerCapabilitiesConstants.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PositionUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/QuarkusPropertiesUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCodeActionsTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java
CodeAction to fix unknown property by proposing similar name
Fixes #80
> CodeAction to fix unknown property by proposing similar name

- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/commons/ExtendedConfigDescriptionBuildItem.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/commons/ExtendedConfigDescriptionBuildItem.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/values/PropertyMatcher.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/values/ValuesDefinition.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/values/ValuesRule.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/values/ValuesRulesDescriptor.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/values/ValuesRulesManager.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusDiagnostics.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusHover.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusValidator.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/QuarkusPropertiesUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/resources/com/redhat/quarkus/model/values/quarkus-values-rules.json
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/commons/QuarkusProjectInfoTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesDiagnosticsTest.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesHoverTest.java
Provide a better support for Quarkus property value
Fixes #69
> Provide a better support for Quarkus property value

- quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/core/JDTQuarkusManager.java
- quarkus.jdt/com.redhat.quarkus.jdt.test/projects/maven/config-quickstart/src/main/java/org/acme/config/CustomExtensionConfig.java
- quarkus.jdt/com.redhat.quarkus.jdt.test/src/main/java/com/redhat/quarkus/jdt/core/JDTQuarkusManagerConfigPropertyTest.java
Collection of Quarkus properties doesn't work with @ConfigRoot with Java source file
Fixes #138
> Collection of Quarkus properties doesn't work with @ConfigRoot with Java source file

- quarkus.ls/CHANGELOG.md
> CHANGELOG for 0.0.4

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCodeActions.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/QuarkusPropertiesUtils.java
- quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCodeActionsTest.java
> Create code action for propose similar enum value

- quarkus.jdt/com.redhat.quarkus.jdt.core/META-INF/MANIFEST.MF
- quarkus.jdt/com.redhat.quarkus.jdt.core/pom.xml
- quarkus.jdt/com.redhat.quarkus.jdt.site/pom.xml
- quarkus.jdt/com.redhat.quarkus.jdt.test/META-INF/MANIFEST.MF
- quarkus.jdt/com.redhat.quarkus.jdt.test/pom.xml
- quarkus.jdt/pom.xml
- quarkus.ls/com.redhat.quarkus.ls/pom.xml
> Upversion to 0.0.5-SNAPSHOT

- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ServerCapabilitiesConstants.java
- quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ServerCapabilitiesInitializer.java
> Initialize codeLens provider if required

- microprofile.jdt/com.redhat.microprofile.jdt.core/META-INF/MANIFEST.MF
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/MicroProfileCorePlugin.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/PropertiesProviderRegistry.java
> Move MicroProfileCorePlugin so that it is accessible

- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileCodeActions.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesCodeActionsTest.java
Fixes #150 
Demo:
This PR will never provide a code action for `quarkus.*`.
However in this case:
```
quarkus.unknown.test1=123
quarkus.unknown.test2=123
quarkus.unknown.test3=123
quarkus.unknown.test4=123
```
A code action for `quarkus.unknown.*` will be provided.
One question,
In this case:
```
a.b.c.d.e=123
a.b.c.d=123
```
If we hover over `a.b.c.d.e`, should we provide a code action per each common ancestor?
```
a.*
a.b.*
a.b.c.*
```
Or should we provide a code action only for the closest common parent?
```
a.b.c.*
```
Currently, this PR provides a code action per each common ancestor.
> Code action for ignore unknown property common parent

- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileHover.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesHoverTest.java
Fixes #168 .
This fix is unrelated to #172 .
> No hover when hover node is nodeType.ASSIGN

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/ArtifactResolver.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/MavenArtifactResolver.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/utils/DependencyUtil.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigRootProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/ConfigItemIntBoolDefaultValueTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/MicroProfileConfigPropertyTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerClassPathKindTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/QuarkusKubernetesTest.java
Download transitive dependencies of deployment JAR
> Download transitive dependencies of deployment JAR

- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/ApplicationPropertiesTextDocumentService.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileProjectInfoCache.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/ls/MicroProfileProjectInfoCacheTest.java
Too many call of microprofile/projectInfo
Fixes #174
> Too many calls of microprofile/projectInfo

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/IPropertiesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManager.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigRootProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusKubernetesProvider.java
> JavaDoc updates

- microprofile.jdt/com.redhat.microprofile.jdt.core/META-INF/MANIFEST.MF
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManager.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/ls/MicroProfileDelegateCommandHandler.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigRootProvider.java
Should add a progress bar / visual clue when loading completion is too
Fixes #58
> Should add a progress bar / visual clue when loading completion is too long

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/providers/MicroProfileRegisterRestClientProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/MicroProfileRegisterRestClientTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileProjectInfoCache.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/ls/MicroProfileProjectInfoWrapperTest.java
Support 6/7 mp-rest properties
See https://github.com/redhat-developer/quarkus-ls/issues/189
> Support 6/7 mp-rest properties

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/metadata/ItemMetadata.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/metadata/ItemMetadata.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/ApplicationPropertiesTextDocumentService.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileLanguageServer.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileProjectInfoCache.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileTextDocumentService.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/api/MicroProfileLanguageServerAPI.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/utils/JSONSchemaUtils.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/utils/JSONSchemaUtilsTest.java
Add support for YAML configuration files
Fixes #112
> Add support for YAML configuration files

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/metadata/ConfigurationMetadata.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/metadata/ItemMetadata.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/AbstractPropertiesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/utils/JDTTypeUtils.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/providers/MicroProfileConfigPropertyProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigPropertiesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigRootProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusKubernetesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/ConfigItemIntBoolDefaultValueTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerClassPathKindTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/QuarkusConfigPropertiesTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/QuarkusConfigRootTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/metadata/ConfigurationMetadata.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/metadata/ItemMetadata.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileDefinition.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/microprofile/model/values/quarkus-values-rules.json
Missing enum value completion/validation for optional enum
Fixes #175
> Missing enum value completion/validation for optional enum

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/MicroProfilePropertiesScope.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/IPropertiesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManager.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/FakeJavaProject.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/utils/DependencyUtil.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/utils/JDTMicroProfileUtils.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigRootProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/GenerateAllPropertiesAndDefinition.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/MicroProfilePropertiesScope.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileProjectInfoCache.java
Compute deployment JAR only when dependencies changed.
> Compute deployment JAR only when dependencies changed.

- microprofile.jdt/com.redhat.microprofile.jdt.core/META-INF/MANIFEST.MF
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/metadata/ConfigurationMetadata.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/metadata/ConverterKind.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/metadata/ItemHint.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/metadata/ItemMetadata.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/AbstractPropertiesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/utils/JDTTypeUtils.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/providers/MicroProfileConfigPropertyProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/io/quarkus/runtime/util/StringUtil.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/JDTQuarkusUtils.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigPropertiesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigRootProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusKubernetesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/GenerateAllPropertiesAndDefinition.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/metadata/ConfigurationMetadata.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/metadata/ConverterKind.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/metadata/ItemHint.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/metadata/ItemMetadata.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileCodeActions.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileCompletions.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileDefinition.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileHover.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/io/quarkus/runtime/util/StringUtil.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesCodeActionsTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesCompletionTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesDefinitionTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesDiagnosticsTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesHoverTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/MicroProfileAssert.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/resources/com/redhat/microprofile/services/all-quarkus-properties.json
Value from Java enum are not correct
Fixes #198
> Value from Java enum are not correct

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/providers/MicroProfileRegisterRestClientProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/MicroProfileRegisterRestClientTest.java
Support for /mp-rest/providers/*/priority
See https://github.com/redhat-developer/quarkus-ls/issues/189
> Support for <mp-rest-client-class-name>/mp-rest/providers/*/priority

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/MicroProfilePropertiesListenerManager.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/ls/MicroProfileDelegateCommandHandler.java
Classpath change listener calling the client is synchronous
Fixes #211
> Classpath change listener calling the client is synchronous

- microprofile.ls/CHANGELOG.md
> Add 0.0.5-SNAPSHOT changelog

- microprofile.jdt/com.redhat.microprofile.jdt.core/META-INF/MANIFEST.MF
- microprofile.jdt/com.redhat.microprofile.jdt.core/pom.xml
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/pom.xml
- microprofile.jdt/com.redhat.microprofile.jdt.site/pom.xml
- microprofile.jdt/com.redhat.microprofile.jdt.test/META-INF/MANIFEST.MF
- microprofile.jdt/com.redhat.microprofile.jdt.test/pom.xml
- microprofile.jdt/pom.xml
- microprofile.ls/com.redhat.microprofile.ls/pom.xml
> Upversion to 0.0.6-SNAPSHOT

- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/empty-gradle-project/gradle/wrapper/gradle-wrapper.properties
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/empty-gradle-project/gradlew
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/empty-gradle-project/gradlew.bat
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/quarkus-gradle-project/gradle/wrapper/gradle-wrapper.properties
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/quarkus-gradle-project/gradlew
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/quarkus-gradle-project/gradlew.bat
> Fix test with gradle.

- microprofile.jdt/com.redhat.microprofile.jdt.core/META-INF/MANIFEST.MF
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/BaseContext.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/BuildingScopeContext.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/IPropertiesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManager.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/SearchContext.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/FakeJavaProject.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/MavenArtifactResolver.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/JDTQuarkusUtils.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigPropertiesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigRootProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusContext.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusKubernetesProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/ProjectLabelTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/QuarkusConfigRootTest.java
Improve performance while getting dependencies of deployment JARs
Fixes #207
> Improve performance while getting dependencies of deployment JARs

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/MicroProfileProjectInfo.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManager.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/MicroProfileProjectInfo.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileProjectInfoCache.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/ls/MicroProfileProjectInfoCacheTest.java
Empty completion after an error from microprofile/projectInfo
Fixes #228
> Empty completion after an error from microprofile/projectInfo

- microprofile.jdt/com.redhat.microprofile.jdt.core/META-INF/MANIFEST.MF
- microprofile.jdt/com.redhat.microprofile.jdt.core/plugin.xml
- microprofile.jdt/com.redhat.microprofile.jdt.core/schema/javaFeatureParticipants.exsd
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerForJava.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/java/AbtractJavaContext.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/java/IJavaCodeLensParticipant.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/java/JavaCodeLensContext.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/java/JavaDiagnosticsContext.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/jaxrs/JaxRsContext.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/project/JDTMicroProfileProject.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/java/JavaFeatureDefinition.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/java/JavaFeaturesRegistry.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/faulttolerance/MicroProfileFaultToleranceConstants.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/faulttolerance/properties/MicroProfileFaultToleranceProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/health/MicroProfileHealthConstants.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/health/java/MicroProfileHealthDiagnosticsParticipant.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/jaxrs/JaxRsConstants.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/jaxrs/java/JaxRsCodeLensParticipant.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/MicroProfileRestClientConstants.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/java/MicroProfileRestClientDiagnosticsParticipant.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/properties/MicroProfileRegisterRestClientProvider.java
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/plugin.xml
- microprofile.jdt/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/jaxrs/java/QuarkusJaxRsCodeLensParticipant.java
Provide codeLens participant
See https://github.com/redhat-developer/quarkus-ls/issues/229
> Provide codeLens participant

- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileFormatter.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesFormatterTest.java
When pasting, the comments gets duplicated when "editor.formatOnPaste":true
Fixes https://github.com/redhat-developer/vscode-quarkus/issues/220
> When pasting, the comments gets duplicated when

- microprofile.jdt/com.redhat.microprofile.jdt.core/plugin.xml
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/jaxrs/JaxRsUtils.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/utils/AnnotationUtils.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/utils/JDTTypeUtils.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/MicroProfileRestClientConstants.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/java/MicroProfileRestClientCodeLensParticipant.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/rest-client-quickstart/src/main/java/org/acme/restclient/CountriesServiceWithBaseUri.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/jaxrs/JaxRsCodeLensTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/jaxrs/JaxRsUtilsTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/restclient/JavaCodeLensMicroProfileRestClientTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/restclient/MicroProfileRegisterRestClientTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileFormatter.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesFormatterTest.java
Provide URL CodeLens for MicroProfile RegisterRestClient
Fixes #167
> Provide URL CodeLens for MicroProfile RegisterRestClient

- microprofile.jdt/com.redhat.microprofile.jdt.test/META-INF/MANIFEST.MF
> Add missing exports for unit tests to be reused

- microprofile.ls/com.redhat.microprofile.ls/pom.xml
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/AbstractTextDocumentService.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/ApplicationPropertiesTextDocumentService.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/JavaTextDocumentService.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileTextDocumentService.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/commons/CodeActionFactory.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileCodeActions.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/ValidationType.java
Consume LSP4J 0.9.0
Fixes #237
> Consume LSP4J 0.9.0

- microprofile.jdt/com.redhat.microprofile.jdt.core/plugin.xml
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/java/codeaction/InsertAnnotationMissingQuickFix.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/java/corrections/proposal/NewAnnotationProposal.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/MicroProfileRestClientConstants.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/MicroProfileRestClientErrorCode.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/java/InjectAndRestClientAnnotationMissingQuickFix.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/java/InjectAnnotationMissingQuickFix.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/java/MicroProfileRestClientDiagnosticsParticipant.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/java/RegisterRestClientAnnotationMissingQuickFix.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/restclient/java/RestClientAnnotationMissingQuickFix.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/health/JavaDiagnosticsMicroProfileHealthTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/restclient/JavaDiagnosticsMicroProfileRestClientTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/internal/core/java/MicroProfileForJavaAssert.java
Support for `MicroProfile RestClient` CodeAction
Fixes #255
> Support for `MicroProfile RestClient` CodeAction

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/java/corrections/proposal/ASTRewriteCorrectionProposal.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/StatusFactory.java
Remove JDT LS dependency for code action.
> Remove JDT LS dependency for code action.

- microprofile.ls/com.redhat.microprofile.ls/pom.xml
> Update com.redhat.microprofile.ls pom for Nexus staging suite

- microprofile.jdt/com.redhat.microprofile.jdt.core/plugin.xml
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/java/codeaction/IJavaCodeActionParticipant.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/java/corrections/proposal/OpenAPIAnnotationProposal.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/java/codeaction/CodeActionHandler.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/java/codeaction/JavaCodeActionDefinition.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/jaxrs/JaxRsConstants.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/openapi/MicroProfileOpenAPIConstants.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/openapi/java/MicroProfileGenerateOpenAPIOperation.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/openapi/java/OpenAPIAnnotationProposal.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/microprofile-openapi/src/main/java/org/acme/openapi/NoOperationAnnotation.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/openapi/GenerateOpenAPIAnnotationsTest.java
To test this PR, open the `NoOperationAnnotation` class from the microprofile-openapi project (used for the tests) and execute code action like the following demo:
> CodeAction to generate OpenAPI annotations

- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/openapi/GenerateOpenAPIAnnotationsTest.java
> Fix Open API codeaction test

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/openapi/java/MicroProfileGenerateOpenAPIOperation.java
Fixes #280 
Signed-off-by: bensonn@ca.ibm.com
> Hide openapi code action if it is not applicable

- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/internal/core/MicroProfilePropertiesListenerManagerTest.java
Ignore test by waiting a fix https://github.com/redhat-developer/quarkus-ls/pull/235
> Ignore classpath changed  test by waiting a fix

- microprofile.jdt/com.redhat.microprofile.jdt.test/pom.xml
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/assembly/projects.xml
> Deploy test projects to download.jboss.org

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/MicroProfilePropertiesListenerManager.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/internal/core/MicroProfilePropertiesListenerManagerTest.java
Classpath changed sends too many microprofile/propertiesChanged notifications
Fixes #206
Signed-off-by: azerr azerr@redhat.com
> Classpath changed sends too many microprofile/propertiesChanged notifications

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManager.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/PropertiesCollector.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/internal/core/PropertiesCollectorTest.java
Duplicate static properties after saving Java files
Fixes #301
> Duplicate static properties after saving Java files

- microprofile.jdt/pom.xml
- Clean up was not done because of 202x years
> Use latest version of the deploy scripts

- microprofile.ls/CHANGELOG.md
> CHANGELOG for 0.0.6

- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/JavaTextDocumentService.java
Completion in non-quarkus/non-mp project causes errors
Fixes https://github.com/redhat-developer/vscode-quarkus/issues/247
> Completion in non-quarkus/non-mp project causes errors

- microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/quarkus/snippets/quarkus-properties.json
Fixes https://github.com/redhat-developer/vscode-quarkus/issues/227
To test the Container Image snippet, please try it with a Quarkus project using a recent version of the Qubernetes extension.
> Edit Datasource snippet

- microprofile.ls/CHANGELOG.md
> CHANGELOG for 0.0.7

- microprofile.ls/README.md
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileCompletions.java
- microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/snippets/SnippetContextForProperties.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesCompletionTest.java
- microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/MicroProfileAssert.java
- quarkus.ls.ext/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/ls/ApplicationPropertiesCompletionTest.java
- quarkus.ls.ext/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/snippets/QuarkusTestPropertiesSnippetRegistryLoader.java
- quarkus.ls.ext/com.redhat.quarkus.ls/src/test/resources/META-INF/services/com.redhat.microprofile.ls.commons.snippets.ISnippetRegistryLoader
- quarkus.ls.ext/com.redhat.quarkus.ls/src/test/resources/com/redhat/quarkus/snippets/quarkus-test-properties.json
Filter properties snippet with properties instead of dependency
Fixes #312
> Filter properties snippet with properties instead of dependency

- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/ProjectLabelInfoEntry.java
- microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/ProjectLabelManager.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/.classpath
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/.dockerignore
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/.project
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/README.md
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/build.gradle
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/gradle.properties
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/gradle/wrapper/gradle-wrapper.properties
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/gradlew
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/gradlew.bat
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/settings.gradle
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/src/main/docker/Dockerfile.jvm
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/src/main/docker/Dockerfile.native
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/src/main/java/org/renamed/GreetingResource.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/src/main/resources/META-INF/resources/index.html
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/src/main/resources/application.properties
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/src/native-test/java/org/renamed/NativeGreetingResourceIT.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/renamed-gradle/src/test/java/org/renamed/GreetingResourceTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/folder-name-different-maven/.classpath
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/folder-name-different-maven/.project
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/folder-name-different-maven/pom.xml
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/folder/empty-maven-project/.classpath
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/folder/empty-maven-project/.project
- microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/folder/empty-maven-project/pom.xml
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/BasePropertiesManagerTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/ProjectLabelTest.java
This is useful when presenting the different projects in a menu,
such as in https://github.com/redhat-developer/vscode-quarkus/issues/215.
> Send project name to the client along with labels.

- microprofile.ls/CHANGELOG.md
> CHANGELOG for 0.0.8

- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/contextpropagation/MicroProfileContextPropagationTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/faulttolerance/MicroProfileFaultToleranceTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/lra/MicroProfileLRATest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/metrics/MicroProfileMetricsTest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/openapi/MicroProfileOpenAPITest.java
- microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/opentracing/MicroProfileOpenTracingTest.java
> Rename static properties test

- quarkus.jdt.ext/pom.xml
> Update deploy folder

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
> Export unit tests

- README.md
- quarkus.jdt.ext/README.md
- quarkus.ls.ext/README.md
> Updated the READMEs with info about lsp4mp

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/JDTQuarkusUtilsTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigPropertiesProvider.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigRootProvider.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusProjectLabelProvider.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/quarkus/JDTQuarkusUtils.java
Add missing test for JDTQuarkusUtils
> Add missing test for JDTQuarkusUtils

- CHANGELOG.md
> CHANGELOG for 0.9.0

- quarkus.jdt.ext/pom.xml
> Use LSP4MP 0.1.0

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/build.properties
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/plugin.properties
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/plugin.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/AbstractStaticQuarkusPropertiesProvider.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusCoreProvider.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/static-properties/quarkus-core-metadata.json
Defines metadata for quarkus core.
> Defines metadata for quarkus core.

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/jaxrs/JaxRsCodeLensTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/jaxrs/java/QuarkusJaxRsCodeLensParticipant.java
Closes redhat-developer/vscode-quarkus#311
> Try to use dev port for JAX-RS url CodeLens

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/scheduler-quickstart/src/main/java/org/acme/scheduler/CounterBean.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/scheduler-quickstart/src/main/resources/application.properties
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/ConfigItemIntBoolDefaultValueTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/MicroProfileConfigPropertyTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/PropertiesManagerClassPathKindTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/PropertiesManagerTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusConfigPropertiesTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusConfigRootTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusHibernateORMPropertyTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusKubernetesTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusScheduledHoverTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusScheduledPropertiesTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/containerimages/QuarkusContainerImagesTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/plugin.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusScheduledHoverParticipant.java
- quarkus.jdt.ext/pom.xml
> Hover support for @Scheduled annoation member values.

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusScheduledPropertiesTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusScheduledPropertiesProvider.java
> Provide sourceType for QuarkusScheduledPropertiesProvider.

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
> Switch to 0.10.0

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/kubernetes/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusKubernetesTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusKubernetesProvider.java
> Collect dependencies of 'quarkus-openshift-deployment'.

- CHANGELOG.md
> CHANGELOG for 0.10.0

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
> Upversion to 0.11.0-SNAPSHOT

- Jenkinsfile
> Add existing build script as a Jenkinsfile

- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/ls/ApplicationPropertiesCompletionTest.java
- quarkus.ls.ext/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/ls/JavaTextDocumentSnippetRegistryTest.java
> Depend on lsp4mp 0.3.0 snapshot build

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
> Change version to 0.10.1

- CHANGELOG.md
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
> Changelog for 0.10.1

- Jenkinsfile
> Add a step to the Jenkinsfile to checkout the repo

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
> Upversion to 0.10.2

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/config/QuarkusConfigJavaHoverTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/ApplicationProfileConfigSource.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigSourceProvider.java
Closes redhat-developer/vscode-quarkus#371
> Support `application-${profile}.properties`

- quarkus.jdt.ext/pom.xml
- Also update Tycho from 1.7.0 to 2.2.0
> Updated jdt.ls target platform version to 1.5.0

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/config-hover/src/main/java/org/acme/config/GreetingResource.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/scheduler-quickstart/src/main/java/org/acme/scheduler/CounterBean.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/config/QuarkusConfigJavaHoverTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/scheduler/QuarkusScheduledHoverTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/scheduler/java/QuarkusScheduledHoverParticipant.java
Added property replacement parameter for `@Scheduled` `cron` attribute property expression.
Fixes #401 
> added property replacement parameter for `@Scheduled` `cron` attribute property expression

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/TemplateParser.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/scanner/TemplateScanner.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/IncludeSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDefinition.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDocumentLink.java
- qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/services/snippets/qute-snippets.json
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/template/scanner/TemplateScannerTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithIncludeSectionTest.java
[qute] parser lenient about new parameters
Fixes #433
> [qute] parser lenient about new parameters

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemResource.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDiagnosticsTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDocumentLinkTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/IQuteErrorCode.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteErrorCode.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaDiagnosticsCollector.java
[qute] Codelenses disappear once @CheckedTemplate is followed by parenthesis
Fixes #439
> [qute] Codelenses disappear once @CheckedTemplate is followed by parenthesis

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/scanner/TemplateScanner.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/template/scanner/TemplateScannerTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
Non tag reported as error
Fixes #443
> Non tag reported as error

- Jenkinsfile
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
> Add Qute artifacts deployment

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/ExpressionParser.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/Part.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Expression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Node.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/scanner/TemplateScanner.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCompletions.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/QuteDocumentSymbolsTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithLetSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInTextTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/toremove/Item.java
- qute.ls/com.redhat.qute.ls/src/test/java/toremove/Review.java
- qute.ls/com.redhat.qute.ls/src/test/java/toremove/TestWithQute.java
- qute.ls/com.redhat.qute.ls/src/test/java/toremove/with.qute
Don't show data model completion inside end tag section
Fixes #446
> Don't show data model completion inside end tag section

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/HelloResource.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDiagnosticsTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDocumentLinkTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/CheckedTemplateSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/TemplateFieldSupport.java
Template sees parameters leaked from other templates
Fixes #465
> Template sees parameters leaked from other templates

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/ExpressionParameter.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Parameter.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/TemplateParser.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/scanner/TemplateScanner.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/scanner/TokenType.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCompletions.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDefinition.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteHighlighting.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/snippets/QuteSnippetContext.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/QutePositionUtility.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/template/TemplateParserTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/template/scanner/TemplateScannerTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithLetSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithIncludeSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/highlighting/QuteHighlightingInSectionTagTest.java
Support {/} end tag section correctly
Fixes #464
> Support {/} end tag section correctly

- quarkus.jdt.ext/pom.xml
- qute.jdt/pom.xml
> Update o.e.jdt.ls.tp dependency to 1.7.0-SNAPSHOT

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/Item.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/InvalidMethodReason.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaTypeInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/InvalidMethodReason.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaTypeInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/JavaDataModelCache.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
Filter methods completion with Qute rules
Fixes #463
> Filter methods completion with Qute rules

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Template.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/TemplateParser.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
Qute validation easily goes out-of-sync when link-editing
Fixes #488
> Qute validation easily goes out-of-sync when link-editing

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/QuteTextDocuments.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/SectionMetadata.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Template.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/TemplateConfiguration.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/LoopSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteHover.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/QuteSearchUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/highlighting/QuteHighlightingInForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithForSectionTest.java
Iteration metadata support not properly implemented
Fixes #468
> Iteration metadata support not properly implemented

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/JavaDataModelCache.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
Fix completion with @TemplateExtension
> Fix completion with @TemplateExtension

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ClientCapabilitiesWrapper.java
Fixed NPE on Qute LS shutdown on Eclipse IDE and other non-VSCode clients
Fixes #493 
> Fixed NPE on Qute LS shutdown on Eclipse IDE

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/ObjectPart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/SectionKind.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/TemplateParser.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/BaseWhenSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/CaseSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/DefaultSectionFactory.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/ElseSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/IsSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/LoopSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteHighlighting.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/QuteSearchUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/highlighting/QuteHighlightingInForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/highlighting/QuteHighlightingInSectionTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/linkededitingrange/QuteLinkedEditingRangeInForSectionTest.java
Loop parameter leak into for-else block
Fixes #482
> Loop parameter leak into for-else block

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMemberInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaMemberInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/ValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
Validate method parameters for template extension
> Validate method parameters for template extension

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMemberInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaMemberInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/ValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/JavaMemberResult.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/JavaDataModelCache.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/commons/JavaMethodInfoTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInValueResolverTest.java
> Validate overloaded methods

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/Parts.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/LiteralSupport.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/JavaDataModelCache.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/AbstractPositionRequest.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/definition/DefinitionRequest.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/hover/HoverRequest.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/QutePositionUtility.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithForSectionTest.java
Validation fail when iterating over integers
Fixes #511
> Validation fail when iterating over integers

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/AssignSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/IfSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/QuteSearchUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInParameterDeclarationTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithCheckedTemplateTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInParameterDeclarationTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWithSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/highlighting/QuteHighlightingInForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/highlighting/QuteHighlightingInIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/highlighting/QuteHighlightingInParameterDeclarationTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInParameterDeclarationTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInTag.java
Support for #if expression
Fixes #436
> Support for #if expression

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/parameter/ParameterParser.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/linkededitingrange/QuteLinkedEditingRangeInForSectionTest.java
NPE in linked editing when deleting variable
Fixes #514
> NPE in linked editing when deleting variable

- qute.ls/com.redhat.qute.ls/pom.xml
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsSyntaxError.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithIncludeSectionTest.java
StringIndexOutOfBoundsException with {@}
Fixes #515
> StringIndexOutOfBoundsException with {@}

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/LiteralSupport.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithLetSectionTest.java
> Literal support as object

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/HelloResource.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDiagnosticsTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDocumentLinkTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/DataModelProject.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/TemplateFieldSupport.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/DataModelProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/commons/datamodel/DataModelProjectTest.java
When used with @Location, templates validation fail
Fixes #522
> When used with @Location, templates validation fail

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/project/datamodel/qute-resolvers.json
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/IfTruthyValueResolverTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/OrEmptyValueResolverTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/OrValueResolverTest.java
Added or and ifTruthy Qute resolvers to resolvers list
Fixes #499
> Added or and ifTruthy Qute resolvers to resolvers list

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithLetSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInParameterDeclarationTest.java
Added support for Qute template for Java simple type hover.
Fixes #502 
> Added support for Qute template Java simple type hover

- quarkus.jdt.ext/pom.xml
- qute.jdt/pom.xml
> Update o.e.jdt.ls.tp dependency to 1.7.0 Release

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/AllQuteSettings.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/settings/SettingsTest.java
Remove quarkus.tools suffix for Qute settings.
> Remove quarkus.tools suffix for Qute settings.

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteWorkspaceService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/client/ConfigurationItemEdit.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/commands/validation/QuteTemplateValidationStatusCommandHandler.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/commands/validation/TemplateValidationStatus.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/PathPatternMatcher.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationSettings.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/SharedSettings.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/settings/PathPatternMatcherTest.java
Support exclusion file for Qute for validation
> Support exclusion file for Qute for validation

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/TemplateParser.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDefinition.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInSectionTagTest.java
NPE on textDocument/definition on unbalanced section
Fixes #556
> NPE on textDocument/definition on unbalanced section

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsSyntaxErrorTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsUserTagTest.java
Ignore undefined variable diagnostic for user tag
Fixes #561
> Ignore undefined variable diagnostic for user tag

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/CustomSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/DefaultSectionFactory.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInSectionTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInUserTag.java
Support parameter expression in user tag
> Support parameter expression in user tag

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/QuteTextDocument.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/PathPatternMatcher.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationSettings.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/FileUtils.java
> Support for untitled uri.

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/Parts.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/scanner/ExpressionScanner.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Expression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTag.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeLens.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/UserTagUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/expression/scanner/ExpressionScannerTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codelens/QuteCodeLensForDataModelTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codelens/QuteCodeLensForUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
> User tag codelens support

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteTextDocumentService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteWorkspaceService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTagRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/DiagnosticDataFactory.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteDiagnosticContants.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ClientCapabilitiesWrapper.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/QuteCapabilityManager.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ServerCapabilitiesConstants.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/UserTagUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInSectionTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsUserTagTest.java
Code action for undefined section tag
> Code action for undefined section tag

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/SectionMetadata.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteHover.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/UserTagUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInUserTag.java
Special keys support for user tag
> Special keys support for user tag

- Jenkinsfile
> build: fix cleanup of qute.jdt update site

- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/ClasspathTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/QuteProjectTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDiagnosticsTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDocumentLinkTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
> fix(test): export tests and refactor QuteProjectTest utility

- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
> fix(test): skip Java 17 related tests

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/MethodPart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/NamespacePart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/ObjectPart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/Parts.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/PropertyPart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/ASTVisitor.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/CData.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Comment.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Expression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Node.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Parameter.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/ParameterDeclaration.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Template.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Text.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/CaseSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/CustomSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/EachSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/ElseSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/ForSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/IfSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/IncludeSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/InsertSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/IsSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/LetSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/SetSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/SwitchSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/WhenSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/WithSection.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/template/ASTVisitorTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/template/CollectObjectPartNameASTVisitor.java
> Need a NodeVisitor class to traverse Qute AST Nodes

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/parameter/scanner/ParameterScanner.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/parameter/scanner/ParameterScannerTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsUserTagTest.java
Support parameter value as String
> Support parameter value as String

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMemberInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/QuteJavaConstants.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateExtensionSupport.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/ExtendedDataModelProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/FieldValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/MethodValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/TypeValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/ValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithLetSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithNamespaceTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInSectionTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java
Support for @TemplateExtension matchName
Fixes #582
> Support for @TemplateExtension matchName

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWithSectionTest.java
Rename code action to "Ignore `UndefinedObject` problem."
> Rename code action to "Ignore `UndefinedObject` problem."

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/commons/JavaMethodInfoTest.java
StringIndexOutOfBoundsException is thrown when computing getter methods
Fixes #600
> StringIndexOutOfBoundsException is thrown when computing getter methods

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/DataModelProviderRegistry.java
Catch error when collect data model is process for a given provider.
> Catch error when collect data model is process for a given provider.

- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
Wrong method parameter resolution (ignores subtypes)
Fixes #608
> Wrong method parameter resolution (ignores subtypes)

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/java/JavaFileTextDocumentService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/BaseSettings.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteCodeLensSettings.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteGeneralClientSettings.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/SharedSettings.java
Support enable/disable CodeLens setting for Qute templates.
Requires redhat-developer/vscode-quarkus/pull/477
> Support enable/disable CodeLens setting for Qute templates

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/com.redhat.qute.jdt.site/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt.test/pom.xml
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/pom.xml
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
> Upversion to 0.12.0-SNAPSHOT

- quarkus.jdt.ext/pom.xml
- qute.jdt/pom.xml
> build: update download.jboss.org IP to reflect infra changes

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Expression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/ExpressionParameter.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Parameter.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/template/TemplateParserTest.java
Expression indexes are wrong
Fixes #627
> Expression indexes are wrong

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/.classpath
- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/StatusesEnum.java
- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/resources/templates/status.qute.html
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt/plugin.xml
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/QuteJavaConstants.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateEnumAnnotationSupport.java
Added support for Qute `@TemplateEnum` annotation
Fixes #485 
> Added support for Qute `@TemplateEnum` annotation

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Parameter.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/QutePositionUtility.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/QuteSearchUtils.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/UserTagUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInForUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/highlighting/QuteHighlightingInUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/linkededitingrange/QuteLinkedEditingRangeInForUserTagTest.java
Linked editing doesn't work if variable is used as a parameter into a section
Fixes https://github.com/redhat-developer/vscode-quarkus/issues/500
> Linked editing doesn't work if variable is used as a parameter into a section

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/ObjectPart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Template.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/ExtendedDataModelProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/JavaDataModelCache.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/FieldValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/MethodValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/TypeValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/ValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCompletableFutures.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDefinition.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithLetSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithNamespaceTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInInfixNotationTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInSectionTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionTest.java
Support for global variables in Qute LS.
> Support for global variables in Qute LS.

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigPropertiesProvider.java
Fixed method void return check in `QuarkusConfigPropertiesProvider`.
Fixes #650 
> Fixed method void return check in `QuarkusConfigPropertiesProvider`

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/Item.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaParameterInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaTypeInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/resolver/AbstractTypeResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaParameterInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaTypeInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/commons/JavaMethodInfoTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/commons/JavaParameterInfoTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/commons/JavaTypeInfoTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInNativeModeTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInParameterDeclarationTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInValueResolverTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInValueResolverTest.java
Varargs are not properly supported in Qute template validation
Fixes #509
> Varargs are not properly supported in Qute template validation

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/scheduler/java/QuarkusScheduledDefinitionParticipant.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/scheduler/java/QuarkusScheduledHoverParticipant.java
> Moved PropertyReplacerStrategy to correct package

- .gitignore
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
> Update lsp4j to 0.14.0

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/snippets/QuteParentSnippetContext.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/snippets/QuteSnippetRegistryLoader.java
- qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/services/snippets/qute-nested-snippets.json
- qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/services/snippets/qute-snippets.json
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteSnippetCompletionInIfSectionTest.java
Improved completion with `#else` and `#elseif` when nested in Qute `#if` section.
Part of #497
> Improved completion when nested in Qute `#if` section

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/pom.xml
See https://github.com/eclipse/lsp4mp/pull/267, https://github.com/eclipse/lsp4mp/pull/268, https://github.com/eclipse/lsp4mp/pull/269
> Adapt to new version of m2e in JDT-LS

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/HelloResource.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDiagnosticsTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDocumentLinkTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/AnnotationLocationSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaCodeLensCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaDiagnosticsCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaDocumentLinkCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateFieldSupport.java
When Template is constructor-injected, @Location is ignored
Fixes #637
> When Template is constructor-injected, @Location is ignored

- Jenkinsfile
> Update Jenkinsfile to use Java 17

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/com.redhat.qute.jdt.site/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt.test/pom.xml
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/pom.xml
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
> Upversion to 0.13.0

- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/pom.xml
- Update JDT-LS to 1.14.0 Release
- Update LSP4MP to 0.6.0 SNAPSHOT
> Update dependencies to latest versions.

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownMethod.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java
Added similar text suggestions Qute CodeAction(s)  for `UnknownMethod`
Part of #670 and #602
> Added Qute CodeAction(s) for similar text suggestions for `UnknownMethod`

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/QuteJavaDefinitionParams.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/QuteJavaDefinitionParams.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteInlayHint.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteLanguageService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/inlayhint/InlayHintASTVistor.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/QuteInlayHintTest.java
Clickable InlayHint for Java type
Fixes #702
> Clickable InlayHint for Java type

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/ls/QuteSupportForTemplateDelegateCommandHandler.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/AbstractTextDocumentService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteTextDocumentService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteLanguageClientAPI.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteTemplateJavaTextEditProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteLanguageService.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/CodeActionRequest.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/CodeActionResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/CodeActionResolverKind.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/CodeActionUnresolvedData.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownProperty.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionResolverForGenerateMissingMember.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteTemplateCodeActionResolvers.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteCodeActionSettings.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/SharedSettings.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/QuteCapabilityManager.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ServerCapabilitiesConstants.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ServerCapabilitiesInitializer.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/JSONUtility.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteGenerateMissingMemberCodeActionTest.java
> codeAction/resolve support for qute-ls

- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWhenSectionTest.java
> Provide validation for data model for #switch section

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/QutePositionUtility.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithLetSectionTest.java
ClassCastException with code action and method part
Fixes #717
> ClassCastException with code action and method part

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java
> Check with qualified name of Template fields in AbstractQuteTemplatinkCollector

- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
Ignore synthetic method in Qute template
Fixes #723
> Ignore synthetic method in Qute template

- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaTypeInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaTypeKind.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/JavaTypesSearch.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/JDTTypeUtils.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaTypeInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaTypeKind.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/CaseOperator.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/BaseWhenSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithWhenSectionTest.java
> Provide completion for enum in #switch section

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/LineIndentInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/TextDocument.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/snippets/SnippetRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/snippets/SnippetsBuilder.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Template.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/CompletionRequest.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForParameterDeclaration.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForSnippets.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteCompletionSettings.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/StringUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithInsertTextModeTest.java
Indent snippet new line if LSP client doesn't support InsertTextMode#AdjustIndentation
Fixes #727
> Indent snippet new line if LSP client doesn't support InsertTextMode#AdjustIndentation

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/CaseSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWhenSectionTest.java
> Validate operator in #case and #is section

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/CaseOperator.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Operator.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/CaseSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/IfSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCompletions.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDefinition.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithWhenSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWhenSectionTest.java
> Support completion for operator in #case #is sections

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDefinition.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionInWhenSectionTest.java
> Fix missing definition for #case section Enum with operator name

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/CaseOperator.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/DocumentableItem.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Operator.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/CaseSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/MethodValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteHover.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInExpressionWithWhenSectionTest.java
> Support hover for operators in #case section

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
> fix: Missing exports from quarkus test bundle

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTagRegistry.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCompletions.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionForTagSection.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForSnippets.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithCheckedTemplateTest.java
> Prevent duplicate completion items in Qute templates

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/ConfigItemIntBoolDefaultValueTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/MicroProfileConfigPropertyTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/PropertiesManagerClassPathKindTest.java
> Fix tests by taking into account new property from lsp4mp

- quarkus.ls.ext/com.redhat.quarkus.ls/src/main/resources/com/redhat/quarkus/snippets/quarkus-java.json
- quarkus.ls.ext/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/ls/JavaTextDocumentSnippetRegistryTest.java
> Add new snippet `qitrc` to create an integration test class

- CHANGELOG.md
> Changelog for 0.13.0

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/com.redhat.qute.jdt.site/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt.test/pom.xml
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/pom.xml
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
> Upversion to 0.14.0

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/QuteSupportForTemplateGenerateMissingJavaMemberHandler.java
> Remove dead code from a Qute CodeAction

- Jenkinsfile
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
> Use Maven settings from ENV during Nexus deploy

- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGenerateMissingJavaMemberTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/QuteSupportForTemplateGenerateMissingJavaMemberHandler.java
> Prevent infinite loop in code action

- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/ls/JavaTextDocumentSnippetRegistryTest.java
- qute.jdt/pom.xml
> Update jdt.ls to 1.20.0, fix tests for lsp4mp 0.7.0

- quarkus.ls.ext/com.redhat.quarkus.ls/src/main/resources/com/redhat/quarkus/snippets/quarkus-java.json
- quarkus.ls.ext/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/ls/JavaTextDocumentSnippetRegistryTest.java
> Context-aware Java snippets

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/ObjectPartCollector.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTag.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDefinition.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/definition/QuteDefinitionWithUserTagTest.java
Definition for user tag parameter
Fixes #789
> Definition for user tag parameter

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/extensions/renarde/RenardeResolvedJavaTypeFactory.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/html/scanner/HtmlScanner.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/html/scanner/ScannerState.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/html/scanner/TokenType.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/CodeActionRequest.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForMissingInputs.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/CollectHtmlInputNamesVisitor.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/html/scanner/HtmlScannerTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/template/ASTVisitorTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithFormSectionTest.java
> Add CodeAction to insert expected input for renarde #form

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/RenardeCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithFormSectionTest.java
> Fix bug with duplicate code action for 'MissingExpectedInput'

- .gitleaks.toml
> Add .gitleaks.toml to ignore false positive leaks

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTag.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForMissingInputs.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForMissingParameters.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/resources/templates/tags/inputRequired.html
> Add CodeAction to insert missing user tag parameters

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/ObjectPart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsForSyntax.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
Support ! operator in #if without incrementing the part start offset
Fixes #816
> Support ! operator in #if without incrementing the part start offset

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java
ResolvedJavaTypeInfo fromJDT synchronized with ResolvedJavaTypeInfo from LS
> ResolvedJavaTypeInfo fromJDT synchronized with ResolvedJavaTypeInfo from LS

- CHANGELOG.md
> CHANGELOG for 0.14.0

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/com.redhat.qute.jdt.site/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt.test/pom.xml
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/pom.xml
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
> Upversion to 0.14.1

- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverKind.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverKind.java
uri: and uriabs: no longer work as expected
Fixes #850
> uri: and uriabs: no longer work as expected

- CHANGELOG.md
> CHANGELOG for 0.14.1

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTag.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForMissingParameters.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithIncludeSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/resources/templates/tags/myTag.html
> Remove unexpected nested-content parameter inserted in Quick Fix

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForMissingParameters.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/resources/templates/tags/myTag.html
> Fix insert missing parameters code action overwriting existing content

- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/pom.xml
> Use lsp4mp `0.8.0-SNAPSHOT`

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
missing required "title" property when starting Qute LS lead to NPE
Fixes #865
> missing required "title" property when starting Qute LS lead to NPE

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteDataModelProjectProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteJavaCodeLensProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteJavaDefinitionProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteJavaDiagnosticsProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteJavaDocumentLinkProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteJavaTypesProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteJavadocProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteProjectInfoProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteResolvedJavaTypeProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteTemplateJavaTextEditProvider.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteUserTagProvider.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteLanguageClient.java
Don't implement by default custom language client API
Fixes #870
> Don't implement by default custom language client API

- qute.jdt/com.redhat.qute.jdt/plugin.xml
Fix uri renarde description.
See comment from IJ Quarkus at https://github.com/redhat-developer/intellij-quarkus/pull/907#discussion_r1213331316
> Fix uri renarde description.

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
NPE during Qute validation when project is not available
Fixes #886
> NPE during Qute validation when project is not available

- .gitignore
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/quarkus-renarde-todo/src/main/java/rest/Game.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/renarde/RenardeJaxRsTest.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/renarde/java/RenardeJaxRsInfoProvider.java
fixes #892 
Signed-off-by: Fred Bricon <fbricon@gmail.com>
> fix Renarde url computation

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteTextDocumentService.java
Fix NPE with Qute resolve completion when data is not filled.
> Fix NPE with Qute resolve completion when data is not filled.

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Parameter.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithEachSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithForSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithLetSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithNamespaceTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInInfixNotationTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInSectionTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithIncludeSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/resources/templates/tags/bundleStyle.html
Support ? in parameter let section
Fixes #904
> Support ? in parameter let section

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/RenardeDiagnosticsTest.java
Don't report error when javaType is null
Fixes #908
> Don't report error when javaType is null

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/validator/QuteSyntaxErrorCode.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/validator/QuteSyntaxValidator.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/syntax/QuteDiagnosticsEndDotSyntaxErrorTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/syntax/overrided/QuteDiagnosticsSectionSyntaxErrorTest.java
{name. ?: "Qute"} doesn't report a validation error
Fixes #884
> {name. ?: "Qute"} doesn't report a validation error

- quarkus.jdt.ext/pom.xml
- qute.jdt/pom.xml
- Also update to lsp4mp 0.9.0-SNAPSHOT releases
> Update eclipse.jdt.ls to 1.27.0-SNAPSHOT

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/com.redhat.qute.jdt.site/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt.test/pom.xml
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/pom.xml
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
> Upversion to 0.17.0

- quarkus.jdt.ext/.mvn/wrapper/MavenWrapperDownloader.java
- quarkus.jdt.ext/.mvn/wrapper/maven-wrapper.properties
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/mvnw
- quarkus.jdt.ext/mvnw.cmd
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/.mvn/wrapper/MavenWrapperDownloader.java
- quarkus.ls.ext/com.redhat.quarkus.ls/.mvn/wrapper/maven-wrapper.properties
- quarkus.ls.ext/com.redhat.quarkus.ls/mvnw
- quarkus.ls.ext/com.redhat.quarkus.ls/mvnw.cmd
- qute.jdt/.mvn/wrapper/MavenWrapperDownloader.java
- qute.jdt/.mvn/wrapper/maven-wrapper.properties
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/mvnw
- qute.jdt/mvnw.cmd
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/.mvn/wrapper/MavenWrapperDownloader.java
- qute.ls/com.redhat.qute.ls/.mvn/wrapper/maven-wrapper.properties
- qute.ls/com.redhat.qute.ls/mvnw
- qute.ls/com.redhat.qute.ls/mvnw.cmd
- React to org.apache.commons.io -> org.apache.commons.commons-io
This will require a snapshot build of https://github.com/eclipse/lsp4mp/pull/422 .
> Update eclipse.jdt.ls to 1.28.0-SNAPSHOT

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteLanguageServerAPI.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteProjectInfoProvider.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteLanguageClient.java
Move provectAdded / projectRemoved to language server.
> Move provectAdded / projectRemoved to language server.

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteTextDocumentService.java
Delegate kotlin file *.kt to java document service
> Delegate kotlin file *.kt to java document service

- CHANGELOG.md
- Jenkinsfile
Signed-off-by: Fred Bricon <fbricon@gmail.com>
> Skip tests for release (too flaky/slow for Jenkins)

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/RenardeCompletionInExpressionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/RenardeDiagnosticsTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/RenardeHoverTest.java
fix: Support for void in property part of Qute template
Fixes #961
> fix: Support for void in property part of Qute template

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/static-properties/quarkus-hibernate-orm-metadata.json
> fix: added quarkus.hibernate-orm.database.generation 'validate' value

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigPropertiesProvider.java
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigRootProvider.java
- quarkus.jdt.ext/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemResourceWithCustomBasePath.java
- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemTemplatesCustomBasePath.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDiagnosticsTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDocumentLinkTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/QuteJavaConstants.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaCodeLensCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaDiagnosticsCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaDocumentLinkCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/CheckedTemplateSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateFieldSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateRecordsSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/AnnotationUtils.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/JDTQuteProjectUtils.java
fix: qute(NoMatchingTemplate) if using @CheckedTemplate with basePath
Fixes https://github.com/redhat-developer/vscode-quarkus/issues/787
> fix: qute(NoMatchingTemplate) if using @CheckedTemplate with basePath

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-record/src/main/java/org/acme/sample/SomeService.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/resolver/AbstractTypeResolver.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/resolver/ITypeResolver.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateRecordsSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/QuteReflectionAnnotationUtils.java
Support for inner Enum
Fixes #963
> Support for inner Enum

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-record/src/main/java/org/acme/sample/ItemResource.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDiagnosticsTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDocumentLinkTest.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/QuteJavaConstants.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaCodeLensCollector.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/CheckedTemplateSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateFieldSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateRecordsSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/JDTQuteProjectUtils.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/TemplateNameStrategy.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/io/quarkus/runtime/util/StringUtil.java
feat:Qute: Cannot locate hyphenated template name
Fixes #975
> feat:Qute: Cannot locate hyphenated template name

- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemTemplates.java
- qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/ItemTemplatesIgnoreFragments.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
fix: Qute fragments doesn't work with non inner Templates Java file
Fixes #937
> fix: Qute fragments doesn't work with non inner Templates Java file

- CHANGELOG.md
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/com.redhat.qute.jdt.site/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt.test/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/pom.xml
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/CheckedTemplateSupport.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateRecordsSupport.java
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
Version 18 release duplicate key issue
Fixes https://github.com/redhat-developer/vscode-quarkus/issues/822
> Version 18 release duplicate key issue

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/com.redhat.qute.jdt.site/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt.test/pom.xml
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/pom.xml
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
> Bump to 0.19.2

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/inlayhint/QuteInlayHintTest.java
NPE with {# and Qute inlay hint
Fixes #991
> NPE with {# and Qute inlay hint

- quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/OllamaItemMetadataProvider.java
fix: NPE document with Ollama support when Java sources are saved.
> fix: NPE document with Ollama support when Java sources are saved.

- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/pom.xml
- Also Update to eclipse.jdt.ls 1.41.0-SNAPSHOT.
> Update to LSP4MP 0.13.0-SNAPSHOT.

- CHANGELOG.md
> chore: changelog 0.20.0

- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/QuteAssert.java
- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/QuteJavaConstants.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateExtensionAnnotationSupport.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/ExtendedDataModelProject.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/FieldValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/MethodValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/TypeValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/ValueResolver.java
- qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/project/datamodel/resolvers/qute-resolvers.jsonc
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
- qute.ls/com.redhat.qute.ls/src/test/resources/com/redhat/qute/project/roq/RoqDataModel.json
Support TemplateExtension matchNames
Fixes #1013
> Support TemplateExtension matchNames

- quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/OllamaConstants.java
- quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/OllamaItemMetadataProvider.java
- quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/OllamaPropertyValidatorParticipant.java
Add completion support for quarkus.langchain4j.ollama.embedding-model.model-id
Fixes #1014
> Add completion support for quarkus.langchain4j.ollama.embedding-model.model-id

- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGenerateMissingJavaMemberTest.java
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/TemplateGenerateMissingJavaMember.java
> Proper fix for comments in TemplateExtension quickfix test

- qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
- qute.jdt/com.redhat.qute.jdt/plugin.xml
- qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateGlobalAnnotationSupport.java
feat: support for global namespace
Same PR for JDT than IJ https://github.com/redhat-developer/intellij-quarkus/pull/1410
> feat: support for global namespace

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/MethodPart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/NamespacePart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/ObjectPart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/Part.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/PropertyPart.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Template.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/JavaDataModelCache.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProjectRegistry.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/qute_web/QuteWebProject.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/qute_web/QuteWebCompletionsTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/qute_web/QuteWebDiagnosticsTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/inlayhint/qute_web/QuteWebInlayHintTest.java
- qute.ls/com.redhat.qute.ls/src/test/resources/com/redhat/qute/project/qute_web/HttpServletRequest.json
- qute.ls/com.redhat.qute.ls/src/test/resources/com/redhat/qute/project/qute_web/QuteWebDataModel.json
> fix: False-positive error on let-defined variable

- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/pom.xml
> Update lsp4mp to 0.13.2

- quarkus.jdt.ext/pom.xml
- qute.jdt/pom.xml
> Update to tycho 4.0.10

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationSettings.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsSeverityTest.java
Warning instead of error (configurable) for unknown sections
Fixes #1042
> Warning instead of error (configurable) for unknown sections

- CHANGELOG.md
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
- quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- qute.jdt/com.redhat.qute.jdt.site/pom.xml
- qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt.test/pom.xml
- qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
- qute.jdt/com.redhat.qute.jdt/pom.xml
- qute.jdt/pom.xml
- qute.ls/com.redhat.qute.ls/pom.xml
Upversion to 0.22.0, since some of the changes are new features.
> Changelog for 0.22.0

- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWhenSectionTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInUserTagTest.java
- qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/project/AbstractQuteDiagnosticsInProjectTest.java
> Fix test failures caused by diagnostic severity change

- quarkus.jdt.ext/pom.xml
- quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
- Once a new build of lsp4mp is out, this should start to succeed.
> Update to LSP4MP 0.14.2-SNAPSHOT repository.

- qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/documents/QuteClosedTextDocuments.java
fix: close file stream with Files.walk
> fix: close file stream with Files.walk
