quarkus.ls/com.redhat.quarkus.ls/pom.xml
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusLanguageServer.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/VersionHelper.java
quarkus.ls/com.redhat.quarkus.ls/src/main/resources/version.properties

Fixes #13 
Some of the code from this [commit](https://github.com/angelozerr/lsp4xml/commit/edfee175e923a9f2c3a553e240c833280e9cec21) was used for this PR. 
I kept the copyright header as is, for `VersionHelper.java`.

Log Quarkus LS version and Java home version on initialization

---

quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusLanguageServer.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusTextDocumentService.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusHover.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/QuarkusHoverSettings.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/SharedSettings.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PositionUtils.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PropertiesScannerUtils.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesHoverTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java

Fixes #6 
Example:
I did not write tests for this feature yet.
I also did not write an extension/participant for hover.
I might be wrong, but I think there are some small problems with [`PropertiesScannerUtils.java`](https://github.com/xorye/quarkus-ls/blob/3a32cc72b7300f91dbdebad7b3a311ce9915d3bb/quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PropertiesScannerUtils.java). More specifically [here](https://github.com/xorye/quarkus-ls/blob/3a32cc72b7300f91dbdebad7b3a311ce9915d3bb/quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PropertiesScannerUtils.java#L135) and [here](https://github.com/xorye/quarkus-ls/blob/3a32cc72b7300f91dbdebad7b3a311ce9915d3bb/quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/PropertiesScannerUtil …

Implement hover for application.properties keys

---

quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesHoverTest.java

On Windows OS, the line separator is \r\n. This PR fix that. The hard coded \n comes from the Javadoc of Quarkus properties (see META-INF/quarkus-javadoc.properties files from JAR)

Fix hover test on Windows

---

quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/jdt/core/JDTQuarkusManager.java

This PR fixes https://github.com/redhat-developer/quarkus-ls/issues/35
It extract Javadoc only from META-INF/quarkus-javadoc.properties and not from java sources or attached Javadoc. To have a best renderer in markdown it should be better to transform HTML Javadoc to markdown. See issue https://github.com/redhat-developer/quarkus-ls/issues/40

Get javadoc from only META-INF/quarkus-javadoc.properties

---

quarkus.ls/.vscode/launch.json

Fixes https://github.com/redhat-developer/vscode-quarkus/issues/35
The fix is two PRs. This one and https://github.com/redhat-developer/vscode-quarkus/pull/41
The port was changed from 1054 to 1064.

Change debug port for Quarkus language server

---

quarkus.ls/.vscode/settings.json
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusLanguageServer.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusTextDocumentService.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ClientCapabilitiesWrapper.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/QuarkusCapabilityManager.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ServerCapabilitiesConstants.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ServerCapabilitiesInitializer.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/settings/capabilities/QuarkusCapabilitiesTest.java

Fixes #14 
For completion and hover, if the client supports dynamic registration, they are both registered in `QuarkusCapabilityManager.java`.

Manage completion and hover capability dynamically

---

quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusValidator.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesDiagnosticsTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/settings/SettingsTest.java

Fixes #3 
This PR replaces #36 
The error range covers the property key:
The error message:
```
Missing equals sign after 'quarkus.datasource.min-size'quarkus(syntax)
Missing equals sign after 'quarkus.hibernate-orm.log.sql'quarkus(syntax)
```

Implement syntax error for application.properties missing equals sign

---

quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusValidator.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesDiagnosticsTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/settings/SettingsTest.java

Fixes #27 
In this PR, only the duplicate property(s) have a warning range:
@angelozerr , I'm not sure if this is what you meant storing the property in a set. Please let me know if I should change anything.

Implement duplicate properties warning

---

quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java

Fixes #47 
To keep track of existing key names, I am using a set of strings.
[This check](https://github.com/xorye/quarkus-ls/blob/0692081d98ca1a68c01f8380c21db496d032f36c/quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java#L166-L167) is to include the current property key for completion if the current node's name is equal to the current property key. This allows you to get the completion item for the current property when the cursor is at the end like so:

Remove existing Quarkus properties in completion items

---

quarkus.jdt/com.redhat.quarkus.jdt.core/src/main/java/com/redhat/quarkus/commons/ExtendedConfigDescriptionBuildItem.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/commons/ExtendedConfigDescriptionBuildItem.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/Property.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusValidator.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/QuarkusValidationSettings.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/QuarkusPropertiesUtils.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesDiagnosticsTest.java

Fixes #33
This PR provides type validation for enums integer, boolean and float.
@angelozerr , does the ExtendedConfigDescriptionBuildItem.java file from quarkus.ls and quarkus.jdt.core have to be the same? 

Validate application.properties value type

---

quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/model/PropertiesModel.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/parser/PropertiesModelTest.java

Set start offset for PropertiesModel to 0

---

quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusHover.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusModel.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/utils/DocumentationUtils.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesHoverTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java

Fixes #89 
This PR adds the documentation specified in #89, and does not use markdown rendering.

Add documentation for default profiles

---

quarkus.ls/CHANGELOG.md
quarkus.ls/README.md

This PR adds a changelog that contains finished issues specific to the quarkus-ls.
The list of issues for the changelog were the issues from quarkus-ls that had a milestone of "1.1.0"

Add CHANGELOG.md, update README.md

---

quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusTextDocumentService.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/commons/CodeActionFactory.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCodeActions.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusValidator.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/ValidationType.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCodeActionsTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesRequiredCodeActionTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesRequiredDiagnosticsTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java

Fixes #111
To test this PR, change the required validation severity to "error" or "warning". 
Here is a quick demo:
The errors after the code actions are "Missing value" errors.
The spacing on the equals sign is dependent on the user's formatting setting.
It would be great if the "Add all missing required properties" code action was the first code action in the list of code actions that VS Code provided in that gif, however the order of code actions in the `codeActions` list [here](https://github.com/xorye/quarkus-ls/blob/4f33ef1abd5d521407a382f3b7be69018e6aa11b/quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCodeActions.java#L61) doesn't seem to correspond with the order of code actions presented in VS Code.

Implement code action for missing required

---

quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusLanguageServer.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/QuarkusTextDocumentService.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/api/QuarkusLanguageServerAPI.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/commons/client/CommandCapabilities.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/commons/client/CommandKind.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/commons/client/CommandKindCapabilities.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/commons/client/ConfigurationItemEdit.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/commons/client/ConfigurationItemEditType.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/commons/client/ExtendedClientCapabilities.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCodeActions.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/QuarkusCommandCapabilities.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/SharedSettings.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/ClientCapabilitiesWrapper.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/InitializationOptionsExtendedClientCapabilities.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/QuarkusCapabilityManager.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCodeActionsTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesRequiredCodeActionTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/settings/capabilities/QuarkusCapabilitiesTest.java

Fixes #81 
I have a few comments about this PR:
To test this PR, this PR: https://github.com/redhat-developer/vscode-quarkus/pull/152 from vscode-quarkus is needed.
In this PR, the extended capability that deals with whether or not the client is able to update their settings was named [`ExtendedClientSettingsUpdateCapabilities`](https://github.com/xorye/quarkus-ls/blob/81codeaction_unknown/quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/client/ExtendedClientSettingsUpdateCapabilities.java).
For the client to register the capability, the client must have their initialization options like so:
```
initializationOptions: {
extendedClientCapabilities: {
clientSettingsUpdate: { supported: true }
}
}
```
The PR from vscode-quarkus mentioned above, already does this.
The …

Implement code action to add unknown property to exclude array

---

quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/ls/ApplicationPropertiesTextDocumentService.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusCompletions.java
quarkus.ls/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/services/QuarkusLanguageService.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/ApplicationPropertiesCompletionTest.java
quarkus.ls/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/services/QuarkusAssert.java

This PR adds spaces surrounding the equals sign during completion, if the **Quarkus > Tools > Formatting > Surround Equals With Spaces** setting is enabled.
To test this PR, in vscode-quarkus, enable the **Quarkus > Tools > Formatting > Surround Equals With Spaces** setting, and invoke completion in `application.properties` and hit Enter on any completion option.
Before this PR: 
After this PR:

Use formattingSettings to determine spacing for completion

---

microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/FakeJavaProject.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/ls/JDTUtilsLSImpl.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileDefinition.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesDefinitionTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/resources/com/redhat/microprofile/services/all-quarkus-definitions.json

Fixes #162 
Enums (including java.util.Optional enums) work:
```
quarkus.log.console.async.overflow=BLOCK
quarkus.datasource.transaction-isolation-level=read-uncommitted
quarkus.datasource.dd.transaction-isolation-level=none
quarkus.hibernate-search.elasticsearch.automatic-indexing.synchronization-strategy=queued
```
LIMITATION: 
However currently, go to definiton for logging level values and kubernetes enum values do not work.
```
quarkus.log.level=WARNING
kubernetes.image-pull-policy=Always
```

Go to definiton for enum value

---

microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/ls/MicroProfileDelegateCommandHandler.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/ApplicationPropertiesTextDocumentService.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileProjectInfoCache.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/ls/MicroProfileProjectInfoCacheTest.java

Fixes https://github.com/redhat-developer/vscode-quarkus/issues/185
I added this to the jdt.ls extension here : 
https://github.com/xorye/quarkus-ls/blob/277f609b0bbb07b4900aa354a6ba99a69331ad27/microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/ls/MicroProfileDelegateCommandHandler.java#L132-L134
because the original exception here: https://github.com/redhat-developer/quarkus-ls/blob/master/microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManager.java#L88
was being thrown while inside of a Java Job. Because of that, the `exceptionally` stage wasn't being reached on the client side here:
https://github.com/xorye/quarkus-ls/blob/277f609b0bbb07b4900aa354a6ba99a69331ad27/microprofi …

Fix NPE in CompletableFuture on LSP requests

---

microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/MicroProfileJavaCodeLensParams.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerForJava.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/project/AbstractConfigSource.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/project/IConfigSource.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/project/JDTMicroProfileProject.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/project/JDTMicroProfileProjectManager.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/project/PropertiesConfigSource.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/BasePropertiesManagerTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/JavaCodeLensTest.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/MicroProfileJavaCodeLensParams.java

Support microprofile-config.properties on JDT LS side
See https://github.com/redhat-developer/vscode-quarkus/issues/181

Support microprofile-config.properties on JDT LS side

---

microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/PropertiesModel.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/Property.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/parser/PropertiesParser.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileCompletions.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/parser/PropertiesModelTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesHoverTest.java

Fixes #172 by providing accurate start and end offsets for the `Assign` (equals sign) for the `PropertiesModel`.
For example, for this application.properites file:
```
quarkus.application.name = name
```
PropertyKey
start: 0
end: 24
Assign
start: 26
end: -1
PropertyValue
start: 27
end: 31
PropertyKey
start: 0
end: 24
Assign
start: **25**
end: **26**
PropertyValue
start: 27
end: 31

Accurate Assign start and end offsets

---

microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/Node.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/PropertiesModel.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/Property.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/PropertyKey.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/PropertyValue.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/parser/PropertiesHandler.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/model/parser/PropertiesParser.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileFormatter.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileSymbolsProvider.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/parser/PropertiesModelTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesCompletionTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesDiagnosticsTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesFormatterTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesSymbolsTest.java

This PR updates the properties model parser to support multi-line values.
Before this PR:
Before this PR, since multi-line values were not supported, the second and third lines were being parsed as property keys, causing the 'unknown property' diagnostics.
After this PR:
Example content used in the images:
```
quarkus.application.name= quarkus \
application \
name
```

Parse PropertyValue when spanning multiple lines

---

microprofile.jdt/com.redhat.microprofile.jdt.core/META-INF/MANIFEST.MF
microprofile.jdt/com.redhat.microprofile.jdt.test/META-INF/MANIFEST.MF
microprofile.jdt/com.redhat.microprofile.jdt.test/pom.xml
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/BasePropertiesManagerTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/GenerateAllPropertiesAndDefinition.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/JavaHoverTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerClassPathKindTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerLocationTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/QuarkusConfigPropertiesTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/faulttolerance/MicroProfileFaultToleranceTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/health/JavaDiagnosticsMicroProfileHealthTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/jaxrs/JaxRsCodeLensTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/restclient/JavaCodeLensMicroProfileRestClientTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/restclient/JavaDiagnosticsMicroProfileRestClientTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/internal/core/utils/JDTQuarkusUtilsTest.java

- Add Eclipse-ExtensibleAPI to jdt.core so that Eclipse understands it will be extended by test fragment
- Add to remove the jdt.quarkus dependency from the test dependency as it cause cyclic loop in Eclise
- Add jdt.quarkus to the test jdt.test runtime
- Update tests to use static variable

Refactor unit test so that they can be reused

---

microprofile.ls/README.md
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/JavaTextDocumentService.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/commons/snippets/ISnippetContext.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/commons/snippets/ISnippetRegistryLoader.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/commons/snippets/Snippet.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/commons/snippets/SnippetDeserializer.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/commons/snippets/SnippetRegistry.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/commons/snippets/TextDocumentSnippetRegistry.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileCompletions.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/settings/capabilities/ServerCapabilitiesConstants.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/snippets/LanguageId.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/snippets/MicroProfileJavaSnippetRegistryLoader.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/snippets/MicroProfilePropertiesSnippetRegistryLoader.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/snippets/SnippetContextProperties.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/snippets/SnippetContextPropertiesDeserializer.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/quarkus/snippets/QuarkusJavaSnippetRegistryLoader.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/quarkus/snippets/QuarkusPropertiesSnippetRegistryLoader.java
microprofile.ls/com.redhat.microprofile.ls/src/main/resources/META-INF/services/com.redhat.microprofile.ls.commons.snippets.ISnippetRegistryLoader
microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/microprofile/snippets/mp-metrics.json
microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/microprofile/snippets/mp-openapi.json
microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/quarkus/snippets/quarkus-java.json
microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/quarkus/snippets/quarkus-properties.json
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/ls/commons/snippets/SnippetRegistryTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesDiagnosticsTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/MicroProfileAssert.java

Manage client snippet on server side
Fixes https://github.com/redhat-developer/vscode-quarkus/issues/119

Manage client snippet on server side

---

microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileCompletions.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesCompletionTest.java

Fixes #161
With this PR, the profile completion text edits cover everything from the start of the line up to the offset that completion was invoked on, therefore the property key and values (if they exist), become untouched.
Before this PR:
After this PR:

Have profile completion not overwrite the whole line

---

microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/AbstractAnnotationTypeReferencePropertiesProvider.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/AbstractPropertiesProvider.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManager.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/utils/JDTTypeUtils.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/config/properties/MicroProfileConfigPropertyProvider.java
microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/config-quickstart/.classpath
microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/config-quickstart/src/main/java/org/acme/config/GreetingConstructorResource.java
microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/config-quickstart/src/main/java/org/acme/config/GreetingMethodResource.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/ConfigItemIntBoolDefaultValueTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/MicroProfileConfigPropertyTest.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerLocationTest.java

Fixes #135 
To test this PR, please use the `config-quickstart` test project. In that project, there will be ConfigProperty properties coming from constructor parameters and regular method (non-constructor) parameters.
Demo:

Properties support for @ConfigProperty on method parameters

---

microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/PropertiesManagerForJava.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/config/java/MicroProfileConfigHoverParticipant.java
microprofile.jdt/com.redhat.microprofile.jdt.test/projects/maven/config-quickstart/src/main/resources/application.properties
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/JavaHoverTest.java

This PR implements hover support for `@ConfigProperty` name, that are bounded to methods.
To test this PR, please open the config-quickstart test project and hover over the `@ConfigProperty` names in the `GreetingConstructorResource` and `GreetingMethodResource` classes:

Hover support for @ConfigProperty name bounded to method parameters

---

microprofile.jdt/com.redhat.microprofile.jdt.core/plugin.xml
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/MicroProfileJavaProjectLabelsParams.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/ProjectLabelInfoEntry.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/ProjectLabelManager.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/core/utils/JDTMicroProfileUtils.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/ls/AbstractMicroProfileDelegateCommandHandler.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/ls/JavaProjectDelegateCommandHandler.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/ls/MicroProfileDelegateCommandHandler.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/ls/MicroProfileDelegateCommandHandlerForJava.java
microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/jdt/internal/core/providers/MicroProfileProjectLabelProvider.java
microprofile.jdt/com.redhat.microprofile.jdt.test/src/main/java/com/redhat/microprofile/jdt/core/ProjectLabelTest.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/MicroProfileJavaProjectLabelsParams.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/ProjectLabelInfoEntry.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/JavaTextDocumentService.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/JavaTextDocuments.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileLanguageServer.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/MicroProfileTextDocumentService.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/api/MicroProfileJavaProjectLabelsProvider.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/ls/api/MicroProfileLanguageClientAPI.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/ls/JavaTextDocumentsTest.java

Bad perfomance when working with non quarkus/MP projects
See https://github.com/redhat-developer/vscode-quarkus/issues/240

Bad perfomance when working with non quarkus/MP projects

---

microprofile.jdt/com.redhat.microprofile.jdt.core/src/main/java/com/redhat/microprofile/commons/metadata/ItemMetadata.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/commons/metadata/ItemMetadata.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/services/MicroProfileValidator.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/utils/JSONSchemaUtils.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesDiagnosticsTest.java

Fixes #261
To test this PR, please open the `microprofile-open-tracing` project and experiment with the `quarkus.jaeger.sampler-param` property in `application.properties`. This property expects the `java.math.BigDecimal` type.
`java.math.BigDecimal` can be represented in different ways, as explained here: https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#BigDecimal(java.lang.String)
This also works for `application.yaml` files.
As for the `java.math.BigInteger` type, I'm not aware of any property with this type, but I added support for it anyways. For the meantime, this can be tested by adding:
```
@ConfigProperty(name = "greeting.BigInteger")
BigInteger bigInteger;
```
in a resource class.

Add support for java.math.BigDecimal and java.math.BigInteger types

---

microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/utils/AntPathMatcher.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesDiagnosticsTest.java

Fixes https://github.com/redhat-developer/vscode-quarkus/issues/237 by allowing a pattern terminating with `*` to match everything, including forward slashes

Allow exclude unknown property pattern * to match forward slashes

---

microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/microprofile/snippets/mp-metrics.json
microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/microprofile/snippets/mp-openapi.json

Part of redhat-developer#265
Adds context `type` to be used when deciding if an annotation should be displayed

Add context to snippets

---

microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/snippets/MicroProfileJavaSnippetRegistryLoader.java
microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/microprofile/snippets/mp-faulttolerance.json
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/ls/JavaTextDocumentSnippetRegistryTest.java

Closes #307 
Add snippets for MicroProfile fault tolerance annotations 
Tested using a quarkus project generated from https://start.microprofile.io/ with fault tolerance enabled, that I updated to use MicroProfile 3.3

Add snippets for microprofile fault tolerance

---

microprofile.ls/com.redhat.microprofile.ls/src/main/resources/com/redhat/quarkus/snippets/quarkus-properties.json
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesCompletionTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/MicroProfileAssert.java

Added the suggested fields to the datasource snippet. Moved the Hibernate ORM portion of the snippet to a separate snippet that only shows up if Hibernate ORM is used by the Quarkus project. Fixes #316.

Fixed datasource snippet

---

README.md
buildAll.bat
buildAll.sh
microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/empty-gradle-project/gradle/wrapper/gradle-wrapper.properties
microprofile.jdt/com.redhat.microprofile.jdt.test/projects/gradle/quarkus-gradle-project/gradle/wrapper/gradle-wrapper.properties
microprofile.ls/com.redhat.microprofile.ls/pom.xml
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/snippets/SnippetContextForProperties.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/commons/JavaVersion.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesCompletionTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/ApplicationPropertiesDiagnosticsTest.java
microprofile.ls/com.redhat.microprofile.ls/src/test/java/com/redhat/microprofile/services/MicroProfileAssert.java
quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
quarkus.ls.ext/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/ls/ApplicationPropertiesCompletionTest.java

- moved quarkus snippet tests to quarkus.ls
- generated microprofile.ls test jar so test classes can be reused in
quarkus tests
- fixed failing tests when running on Java > 12
- added buildAll scripts for convenience
Signed-off-by: Fred Bricon <fbricon@gmail.com>

Fix build failure and other improvements

---

microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/settings/capabilities/IMicroProfileRegistrationConfiguration.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/settings/capabilities/MicroProfileCapabilityManager.java
microprofile.ls/com.redhat.microprofile.ls/src/main/java/com/redhat/microprofile/settings/capabilities/ServerCapabilitiesConstants.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/QuarkusRegistrationConfiguration.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/resources/META-INF/services/com.redhat.microprofile.settings.capabilities.IMicroProfileRegistrationConfiguration

vscode-quarkus should not be a Java formatter
Fixes https://github.com/redhat-developer/vscode-quarkus/issues/166

vscode-quarkus should not be a Java formatter

---

quarkus.ls.ext/com.redhat.quarkus.ls/src/main/resources/com/redhat/quarkus/snippets/quarkus-java.json
quarkus.ls.ext/com.redhat.quarkus.ls/src/test/java/com/redhat/quarkus/ls/JavaTextDocumentSnippetRegistryTest.java

Removes the jax-rs snippets that were included in quarkus-ls. Since they were moved to lsp4mp (See: https://github.com/eclipse/lsp4mp/pull/32)
Note that the snippets were renamed from `qrc` -> `jaxrc` and `qrm` -> `jaxrm` to be runtime agnostic. So this should probably be mentioned in release notes/changelog for vscode-quarkus.
Signed-off-by: Ryan Zegray <ryan.zegray@ibm.com>

Remove jax-rs snippets

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusHibernateORMPropertyTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/plugin.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusHibernateORMProvider.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/static-properties/quarkus-hibernate-orm-metadata.json

- Fixes redhat-developer/vscode-quarkus#317

quarkus.hibernate-orm.database.generation values should be enumerated.

---

Jenkinsfile

Since no GitHub bot is configured for the pipeline, don't use `git push` in the pipeline, as this will fail.
As well, remove the `git commit` and `git tag` operations, since the result of these commands cannot be pushed to the GitHub repo.
Closes #393

Remove git commit, push, and tag from the pipeline

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusConfigPropertiesTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/QuarkusScheduledHoverTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/YamlUtilsTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/config/JavaCodeLensQuarkusRestClientTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/config/QuarkusConfigJavaDefinitionTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/config/QuarkusConfigJavaHoverTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/jaxrs/JaxRsCodeLensTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/build.properties
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/plugin.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/QuarkusConfigSourceProvider.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/providers/YamlConfigSource.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/utils/YamlUtils.java
quarkus.jdt.ext/pom.xml
quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml

See eclipse/lsp4mp#160
This PR moves the `QuarkusConfigSourceProvider` class into quarkus-ls. It also adds all the necessary supporting classes, and introduces snakeyaml as a dependency. Finally, tests related to `application.proeprties` and `application.yaml` are now a part of quarkus-ls.

Move application.properties and application.yaml support to quarkus-ls

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/jaxrs/JaxRsCodeLensTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/jaxrs/java/QuarkusJaxRsCodeLensParticipant.java
quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml

Added `quarkus.http.root-path` property retrieval to Quarkus JaxRs CodeLens.
References eclipse/lsp4mp/pull/174

added quarkus.http.root-path property retrieval to Quarkus JaxRs CodeLens

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/config-mapping/src/main/java/org/acme/validation/ServerClass.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/configmapping/QuarkusConfigMappingASTVisitorTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/plugin.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/QuarkusConstants.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/java/QuarkusConfigMappingASTVisitor.java

Validate that @ConfigMapping annotation can only be placed in interfaces
Fixes #424

Validate that @ConfigMapping annotation can only be placed in interfaces

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/commands/QuteGenerateTemplateContentCommandHandlerTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java

Duplicate items when completing subclass of an object
Fixes #460

Duplicate items when completing subclass of an object

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/scheduler-quickstart/src/main/resources/application.properties
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/scheduler/QuarkusScheduledDefinitionTest.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/plugin.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/QuarkusConstants.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/scheduler/java/QuarkusScheduledDefinitionParticipant.java

Added definition support for `@Scheduled` annotation members which have hover support.
Fixes #377
Expected behaviour:
Requires https://github.com/eclipse/lsp4mp/pull/214

added definition support for `@Scheduled` annotation

---

qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaElementKind.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaParameterInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaElementInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaElementKind.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaFieldInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaParameterInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/commons/JavaFieldInfoTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/commons/JavaMethodInfoTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithEachSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithForSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithLetSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithWithSectionTest.java

Changed Qute embedded Java completion to display simple types instead of resolved name.
Fixes #490 

Changed Qute embedded Java completion to use simple types

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/utils/YamlUtils.java

- CVE-2021-25738
See https://j0vsec.com/post/cve-2021-25738/ . The CVE doesn't really mention snakeyaml directly (opting to mention the dependent library instead), but if you read the post the issue is in snakeyaml.

Use SafeConstructor for Yaml parser instantation.

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/CodeActionFactory.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeLens.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/commands/QuteClientCommandConstants.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteCommandCapabilities.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/QuteCodeLensTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java

CodeAction to disable validation
Fixes #531

CodeAction to disable validation

---

qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/project/datamodel/qute-resolvers.jsonc
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/arrays/ArrayIntegerValueResolverTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/characterescapes/RawValueResolverTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/characterescapes/SafeValueResolverTest.java

Added support for Qute `raw` and `safe` character escape value resolvers.
Fixes #533 

Added support for Qute `raw` and `safe` character escape value resolvers

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/QuteTextDocument.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/AllQuteSettings.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/BaseSettings.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteGeneralClientSettings.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/SharedSettings.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/settings/SettingsTest.java

Settings from workspace folder
This PR provides the capability to manage settings per workspace folder. It means that when you disable the validation with code action, it stores the disable setting in the settings.json of the project (and not in the workspace). It means that:
* you can have several projects in a workspace and validation can be enabled / disabled for some project. The disabled is not global of the workspace.
* As the disables setting is store in settings.json of the project, it's very portable (you can push the .vscode/settings.json in the git and share this settings with the team.

Settings from workspace folder

---

qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java

Generate .html Qute templates by default to be consistent with https://github.com/redhat-developer/vscode-quarkus/issues/450

Generate .html Qute templates by default

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/QuteErrorCode.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationSettings.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteValidationTypeSettings.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWithSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsSeverityTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithCheckedTemplateTest.java

Replaced `UndefinedVariable` by adding validation severity setting for Qute `UndefinedObject` error.
Part of redhat-developer/vscode-quarkus#473

Replaced `UndefinedVariable` by adding validation severity setting for Qute `UndefinedObject` error

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/DiagnosticDataFactory.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWithSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsSeverityTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithCheckedTemplateTest.java

Added CodeAction to set `UndefinedObject` severity to ignore.
Fixes #594 
Extends: #587 

Added CodeAction to set `UndefinedObject` severity to ignore

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/JavaDataModelCache.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java

Fix bug with super method.
This PR fixes the follwoing problem, if you have :
```java
public class SmallItem{}
public class Item extends SmallItem{}
public class BigItem extends Item{}
```
and have an `smalItem.convert(SmallItem o)` method. then calling `item.convert(bigItem)` fails with:
```
`convert` cannot be resolved or is not a method of `org.acme.Item` Java type.
```

Fix bug with super method.

---

Jenkinsfile
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
quarkus.jdt.ext/pom.xml
quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
qute.jdt/com.redhat.qute.jdt.site/pom.xml
qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
qute.jdt/com.redhat.qute.jdt.test/pom.xml
qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
qute.jdt/com.redhat.qute.jdt/pom.xml
qute.jdt/pom.xml
qute.ls/com.redhat.qute.ls/pom.xml

- Use JDK 11 on builds to satisfy deploy plugin requirements

Bump nexus-staging-maven-plugin from 1.6.8 to 1.6.12

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWithSectionTest.java

Added CodeAction to append ?? for `UndefinedObject` and ignored optional object from diagnostic.
Fixes #613 

Added CodeAction to append `??` for `UndefinedObject` and ignored optional object from diagnostic

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/lsp4j/proposed/InlayHint.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/lsp4j/proposed/InlayHintKind.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/lsp4j/proposed/InlayHintLabelPart.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/lsp4j/proposed/InlayHintParams.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/lsp4j/proposed/QuteInlayHintProvider.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/AbstractTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteLanguageClientAPI.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/QuteTextDocument.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Template.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/TemplateInfoProvider.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteInlayHint.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteLanguageService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/ResolvingJavaTypeContext.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/inlayhint/InlayHintASTVistor.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/BaseSettings.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteCodeLensSettings.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteGeneralClientSettings.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteInlayHintSettings.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/QuteInlayHintTest.java

Support for `textDocument/InlayHint`
Fixes #595

Support for `textDocument/InlayHint`

---

quarkus.jdt.ext/pom.xml
quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml

- Update to the next available snapshot release
- The final release of LSP4MP still gets deployed to the snapshot
location, resulting in a failure to resolve snapshot artifacts
post-release

Update Quarkus LS to use LSP4MP 0.5.0 Snapshots.

---

qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/Globals.java
qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/resources/templates/globals.qute.html
qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetDataModelProjectTest.java
qute.jdt/com.redhat.qute.jdt/plugin.xml
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/QuteJavaConstants.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateDataAnnotationSupport.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateExtensionAnnotationSupport.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateGlobalAnnotationSupport.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/JDTTypeUtils.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java

Added support for `@TemplateGlobal` annotation.
Fixes #605 

Added support for `@TemplateGlobal` annotation

---

quarkus.jdt.ext/pom.xml
qute.jdt/pom.xml

- Eventually a proper update to Java 17 will be required

Temporarily use JDT-LS 1.12.0 (instead of SNAPSHOT build)

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteLanguageService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteRename.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ClientCapabilitiesWrapper.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/QuteCapabilityManager.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ServerCapabilitiesConstants.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ServerCapabilitiesInitializer.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/rename/QuteRenameInForSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/rename/QuteRenameInForUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/rename/QuteRenameInIfSectionTest.java

Added rename support for Qute templates
Fixes #492 

Added rename support for Qute templates

---

.gitignore
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/ModelTextDocument.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/ModelTextDocuments.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/ModelValidatorDelayer.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/QuteTextDocument.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/TemplateInfoProvider.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeLens.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCompletions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDefinition.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteHover.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForParameterDeclaration.java

Delays revalidation of edited Qute templates to prevent excessive validation requests. Improves cancel checking in completion.

Delay revalidation after edit and improve cancel checking

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/snippets/AbstractSnippetContext.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/snippets/Snippet.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForSnippets.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/snippets/AbstractQuteSnippetContext.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/snippets/QuteParentSnippetContext.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/snippets/QuteSnippetContext.java
qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/services/snippets/qute-nested-snippets.json
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteSnippetCompletionInEachSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteSnippetCompletionInForSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteSnippetCompletionInIfSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteSnippetCompletionInSwitchSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteSnippetCompletionInWhenSectionTest.java

Improved completion when nested in Qute `for`, `each`, `switch` and `when` sections.
Fixes #497 

Improved completion when nested in Qute `for`, `each`, `switch` and `when` sections

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/condition/scanner/ConditionScanner.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/scanner/ExpressionScanner.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/parameter/scanner/ParameterScanner.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/scanner/MultiLineStream.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/scanner/TemplateScanner.java

Use preinitialized arrays in order to improve the scanner performance.
Addresses #654

Improve TemplateScanner performance

---

qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/services/snippets/qute-nested-snippets.json
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteSnippetCompletionInWhenSectionTest.java

Added nested `else` completion support for `when` section.
Part of #497 

Added nested `else` completion support for `when` section

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
qute.jdt/com.redhat.qute.jdt/pom.xml

- com.google.gson will come from the o.e.jdt.ls.tp target so there is no
need to specify it as a dependency in the pom

Remove unnecessary Gson dependency in pom files.

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/ModelTextDocuments.java

Fix cancel support with CompletableFuture compose

Fix cancel support with CompletableFuture compose

---

qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/resources/templates/hello.qute.html
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Expression.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/JavaDataModelCache.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteLanguageService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/LevenshteinDistance.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/StringUtils.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java

Added Qute `Did you mean ...?` CodeAction(s) for similar text suggestions for `UndefinedNamespace`, `UndefinedObject`.
Fixes #602 

Added similar text suggestion Code Action(s) for UndefinedObject and UndefinedNamespace

---

qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/GenerateMissingJavaMemberParams.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/ls/QuteSupportForTemplateDelegateCommandHandler.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/GenerateMissingJavaMemberParams.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/CodeActionFactory.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/diagnostics/UnknownPropertyData.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/arrays/ArrayLengthValueResolverTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/arrays/ArraySizeValueResolverTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/arrays/ArrayTakeLastValueResolverTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/arrays/ArrayTakeValueResolverTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteGenerateMissingMemberCodeActionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java

When generating CodeActions for missing properties that are referenced in a Qute template, don't suggest adding a field or adding a getter when the type that is being referred to is a binary type (i.e. built-in class or class from an external library).
Similarly, don't suggest creating a template extension for a type whose source code is available.
Fixes #676

Don't show "add field/getter" CodeActions in Qute for binary types

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/ValidatorDelayer.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java

See https://github.com/eclipse/lsp4mp/pull/273 . It turns out we have the same issue in Qute templates. As @angelozerr mentions, if you have a template like :
```
{#for item in items}
{/for}
```
and change `items` quickly, it can occur.
```
[Error - 2:59:06 p.m.] Request textDocument/codeAction failed.
Message: Internal error.
Code: -32603 
java.util.concurrent.CompletionException: java.lang.ClassCastException: class com.redhat.qute.parser.template.sections.ForSection cannot be cast to class com.redhat.qute.parser.expression.ObjectPart (com.redhat.qute.parser.template.sections.ForSection and com.redhat.qute.parser.expression.ObjectPart are in unnamed module of loader 'app')
at java.base/java.util.concurrent.CompletableFuture.encodeThrowa …
```

Do not give CodeActions for stale diagnostics

---

qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGenerateMissingJavaMemberTest.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/GenerateMissingJavaMemberParams.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverKind.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/extensions/quarkus/InjectNamespaceResolverSupport.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/ls/QuteSupportForTemplateDelegateCommandHandler.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/QuteSupportForTemplateGenerateMissingJavaMemberHandler.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateDataAnnotationSupport.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateEnumAnnotationSupport.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateExtensionAnnotationSupport.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateGlobalAnnotationSupport.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/GenerateMissingJavaMemberParams.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/ResolvedJavaTypeInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/resolvers/ValueResolverKind.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/ExtendedDataModelProject.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/JavaDataModelCache.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownProperty.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteGenerateMissingMemberCodeActionTest.java

For CodeActions for a missing member in a Qute template, generate one "add template extension to existing class" CodeAction for each class file that is annotated with @TemplateExtension.
Closes #677

Generate one CodeAction for each template extensions class

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/AbstractTextDocumentService.java

Resolve rename requests to `null` in Java files for qute-ls

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/AbstractQuteCodeAction.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUndefinedNamespace.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUndefinedObject.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownMethod.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownProperty.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUndefinedNamespaceTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUndefinedObjectTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUnknownMethodTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUnknownPropertyTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteGenerateMissingMemberCodeActionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java

Added Qute CodeAction(s) for similar text suggestions for `UnknownProperty`.
Part of #602

Added Qute CodeAction(s) for similar text suggestions for `UnknownProperty`.

---

qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/cyclic/ClassA.java
qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/cyclic/ClassB.java
qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/cyclic/ClassC.java
qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetJavaTypeTest.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownMethod.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnknownProperty.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUnknownMethodTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUnknownPropertyTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionTest.java

Prevent types from being visited twice while collecting type information. This prevents validation, completion, and code actions from freezing when working with objects of classes that have cyclic inheritance.
Closes #725

Prevent infinite recursion in validation, completion, code actions

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Parameter.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/CaseSection.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWhenSectionTest.java

Qute parser does not parse operator parameters with '=' correctly
Fixes #742

Qute parser does not parse operator parameters with '=' correctly

---

buildAll.sh
quarkus.jdt.ext/pom.xml
qute.jdt/pom.xml

- Use a proper release of JDT-LS 1.15.0 as it should be compatible
- Fix buildAll.sh on Linux so it runs all statements without halting

Update Target Platform to 1.16.0-SNAPSHOT version of JDT-LS target.

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/jaxrs/JaxRsCodeLensTest.java

Fix JAX-RS code lens test failures

---

quarkus.jdt.ext/pom.xml
quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
qute.jdt/pom.xml

- Update lsp4mp version to 0.7.0-SNAPSHOT for quarkus.jdt.ext
- Update Tycho 2.7.2 to 3.0.1

Update Target Platform to 1.19.0-SNAPSHOT version of JDT-LS target.

---

qute.ls/com.redhat.qute.ls/pom.xml
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/snippets/Link.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/snippets/Snippet.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/snippets/SnippetDeserializer.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/snippets/SnippetRegistry.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/ASTVisitor.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/DefaultSectionFactory.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/FragmentSection.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java
qute.ls/com.redhat.qute.ls/src/main/resources/com/redhat/qute/services/snippets/qute-snippets.json
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithFragmentSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithIncludeSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/hover/QuteHoverInUserTagTest.java

Provide basic support for #fragment section
This PR provides 
* `#fragment` snippet  completion
* avoid reporting undefined section tag for #fragment
* improve completion and hover documentation fo all sections by adding links at the end of the documentation
See https://github.com/redhat-developer/vscode-quarkus/issues/563

Provide basic support for #fragment section

---

qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/src/main/java/org/acme/qute/MyTemplateExtensions.java
qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGenerateMissingJavaMemberTest.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/TemplateGenerateMissingJavaMember.java

For the "generate missing member" qute-ls CodeAction, generate the missing member at the end of the respective list. i.e. place the new field at the end of the list of fields, or place the new getter method at the end of the list of methods.

Insert newly generated members at end

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/AbstractTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteWorkspaceService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteTemplateProvider.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/java/JavaFileTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/template/TemplateFileTextDocumentService.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/commands/AbstractTemplateCommandHandler.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/commands/QuteSurroundWithCommandHandler.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteLanguageClient.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteLanguageServer.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/commands/QuteSurroundWithCommandHandlerTest.java

Fixes https://github.com/redhat-developer/vscode-quarkus/issues/581

Support surround with section/comments command

---

qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/ProgressSupport.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ClientCapabilitiesWrapper.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProjectRegistry.java

Show validation errors for Qute project without opening a Qute template file
Fixes #813
This PR requires https://github.com/redhat-developer/vscode-quarkus/pull/597 on vscode side

Show validation errors for Qute project without opening a Qute template file

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/CodeActionFactory.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java

Some clients, like VS Code, will attempt to resolve a code action if `edit` is missing, even if a command is provided. In order to prevent this from happening, pass an empty `WorkspaceEdit` object as the `edit` for code actions that run commands.
Fixes redhat-developer/vscode-quarkus#598

Prevent resolving code actions that run commands

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/NamespacePart.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/ObjectPart.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/Part.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/ServerCapabilitiesConstants.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithIfSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java

{if !inject:beanName}{/if} is marked as invalid
Fixes #828

{if !inject:beanName}{/if} is marked as invalid

---

qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-quickstart/.classpath
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/TemplateGenerateMissingJavaMember.java

When locating the folder to generate `TemplateExtension.java` into
during the "generate missing member" Qute quick fix:
- Filter out classpath entries that are in the output (`target`) folder
- Filter out classpath entries that represent test code
- Filter out classpath entries that represent resource folders (folders
with no Java source files)
Fixes #831

Locate spot to generate `TemplateExtensions.java` better

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/projects/maven/quarkus-renarde-todo/src/main/java/rest/Application.java
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/src/main/java/com/redhat/microprofile/jdt/quarkus/renarde/RenardeJaxRsTest.java

Modifies the Renarde WorkspaceSymbol and CodeLens test cases in order to test that those features work on methods without any annotations on them.
Requires eclipse/lsp4mp#376

Tests for Renarde REST methods with no annotations

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeActions.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForMismatchSectionTag.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUnterminatedSection.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/QutePositionUtility.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/syntax/QuteDiagnosticsOverridedSyntaxErrorTest.java

Add CodeActions to resolve syntax errors related to sections

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUndefinedNamespace.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/codeactions/QuteCodeActionForUndefinedObject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUndefinedNamespaceTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUndefinedObjectTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUnknownMethodTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionForSimilarTextSuggestionsForUnknownPropertyTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteCodeActionWithSettingsTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codeaction/QuteGenerateMissingMemberCodeActionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithWithSectionTest.java

Ignore 'UndefinedObject' problem code action should appear only if LSP client can support update configuration.
In IJ Quarkus, it doesn't support the capability to update configuration on client side. In otherwise the `Ignore 'UndefinedObject' problem` should not appear:
This PR checks that LSP client can support the command which update LSP client settings.

Ignore 'UndefinedObject' + 'UndefinedNamespace' problem code action should appear only if LSP client can support update configuration.

---

quarkus.jdt.ext/pom.xml
qute.jdt/pom.xml

See https://github.com/eclipse/eclipse.jdt.ls/pull/2666 . m2e 2.3.0 snapshot repo is gone so the old JDT-LS TP won't build. Need to use a newer one.

Update eclipse.jdt.ls to 1.24.0-SNAPSHOT

---

quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml

This is needed to fix the build, since the 0.8.0-SNAPSHOT have been automatically deleted.

Update lsp4mp to 0.8.0.

---

.github/workflows/tests.yml
quarkus.jdt.ext/pom.xml
qute.jdt/pom.xml

- Automatic JVM detection in JDT Debug seems to have introduced a regression in JDT indexing causing java.lang.OutOfMemory
- Use Eclipse Temurin for JDK distribution.
See https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/231 for (I believe) the root cause.
Note : The property is just a workaround, and will only apply for the tests, so that they can run. I really suspect this would hit people at runtime. I've imported quarkus projects in vscode-quarkus (with vscode-java) and seen the OOM error. :neutral_face:

Use DetectVMInstallationsJob.disabled=true property from JDT Debug

---

qute.ls/com.redhat.qute.ls/pom.xml
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Node.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Section.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/IncludeSection.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/LetSection.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/SetSection.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/validator/QuteSyntaxValidator.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/syntax/QuteDiagnosticsOverridedSyntaxErrorTest.java

Qute now support optional end tags for sections
Fixes #879

Qute now support optional end tags for sections

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Parameter.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTag.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTagParameter.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTagParameterCollector.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/inlayhint/InlayHintASTVistor.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteInlayHintSettings.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java

Fix support ? in parameter let section
Fixes #906
This PR provides the capability to have name as completion item in bundleScript and it displays as hinlay the default value of let . Here a demo:
//cc @ia3andy

Fix support ? in parameter let section

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForParameterDeclaration.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/QuteCompletionSettings.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInNativeModeTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInParameterDeclarationTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithInsertTextModeTest.java

Fixes #900 
* moves `editRange` and `insertTextFormat` to `itemDefaults` when supported

Support itemDefaults for Qute parameter declaration

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java

- Fixes https://github.com/redhat-developer/quarkus-ls/issues/924
See https://github.com/redhat-developer/quarkus-ls/blob/2bbcefc997e044702949b79b62c98b6ebb7b3995/quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigPropertiesProvider.java#L316-L317 . Very similar recursive call, but done correctly.

Prevent StackOverflow by passing types processed in recursive call.

---

qute.jdt/com.redhat.qute.jdt/plugin.xml
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/ProjectInfo.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/ls/QuteSupportForTemplateDelegateCommandHandler.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/JDTQuteProjectUtils.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/ProjectInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/QuteLanguageServer.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/api/QuteProjectInfoProvider.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/sections/IncludeSection.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDocumentLink.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionForTemplateIds.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteLanguageClient.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/multiple/QuteProjectA.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/multiple/QuteProjectB.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/commands/QuteGenerateTemplateContentCommandHandlerTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/multiple/QuteCompletionWithIncludeSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/multiple/QuteDiagnosticsWithIncludeSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/project/AbstractQuteDiagnosticsInProjectTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/documentlink/QuteDocumentLinkTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/documentlink/multiple/QuteDocumentLinkTest.java
qute.ls/com.redhat.qute.ls/src/test/resources/projects/project-a/src/main/resources/templates/root.html
qute.ls/com.redhat.qute.ls/src/test/resources/projects/project-b/src/main/resources/templates/index.html

Qute support for multi module project
Fixes #930

Qute support for multi module project

---

quarkus.jdt.ext/pom.xml

The GH Actions test run workflow doesn't seem to need this but certain environments are hitting OOM running the tests, and this helps. I'm pretty sure there's some regression that was introduced into Eclipse 4.29 but I haven't been able to investigate deeply to find the cause.

Increase XmX to 2G for quarkus.jdt.ext tests.

---

.github/workflows/tests.yml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
quarkus.jdt.ext/pom.xml
qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetJavadocTest.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/ls/JDTUtilsLSImpl.java
qute.jdt/pom.xml

Fixes javadoc for qute, similar to https://github.com/eclipse/lsp4mp/pull/432.
Related to https://github.com/redhat-developer/vscode-quarkus/issues/638

fix: use newer JDT.LS's JavadocContentAccess2 methods

---

qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/template/datamodel/AbstractFieldDeclarationTypeReferenceDataModelProvider.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/parameter/ParameterParser.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/parameter/scanner/ParameterScanner.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/parameter/scanner/ParameterScannerTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInExpressionWithLetSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/inlayhint/QuteInlayHintTest.java

This PR provides the capability to add any spaces between parameters of section
Ex : 
```
{#let foo    =         "bar"       }
{foo}
```
will not report error in `{foo}` because foo can be computed correctly even with extra spaces.

fix: allow spaces inside section branch.

---

qute.jdt/com.redhat.qute.jdt.test/projects/maven/quarkus3/src/main/java/org/acme/Bean3.java
qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/utils/CDIUtilsTest.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/CDIUtils.java

fix: allow inject: with constructor class which have arguments
Same fix than IntelliJ https://github.com/redhat-developer/intellij-quarkus/pull/1351

fix: allow inject: with constructor class which have arguments

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/inlayhint/InlayHintASTVistor.java

fix: separate user tag parameters inlay hint
This PR uses the paddingRight property of inlay hint to separate user tag parameters.
Here the result of vscode:
We will have to support this property in LSP4IJ.

fix: separate user tag parameters inlay hint

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/parameter/scanner/ParameterScanner.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/parameter/scanner/ParameterScannerTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/collections/CollectionsBracketIntegerValueResolverTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/resolvers/collections/CollectionsIntegerValueResolverTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithForSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithIfSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithLetSectionTest.java

fix: Qute highlight errors due to formatting
Fixes #966
This PR fixes the 2 problem of #966 issue:
* avoid having false positive error (when a method in for or each section is used with parameters, those parameters was validated to check if the parameter type was iterable):
* provides thacapability to write spaces inside methode parameters.
@fbricon I had to do a big change in parameter parser. Hopefully we had alo of tests about that, I have written a lot of tests, but I hope I have not boken something.

fix: Qute highlight errors due to formatting

---

qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-record/src/main/java/org/acme/sample/HelloResource.java
qute.jdt/com.redhat.qute.jdt.test/projects/maven/qute-record/src/main/java/org/acme/sample/SomeService.java
qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaCodeLensTest.java
qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDiagnosticsTest.java
qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/java/JavaDocumentLinkTest.java
qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGetResolvedJavaTypeTest.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/QuteSupportForTemplate.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/resolver/AbstractTypeResolver.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/resolver/ITypeResolver.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/template/datamodel/TemplateRecordsSupport.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/QuteReflectionAnnotationUtils.java

The Template record support has introduced a major bug. All records are cosidered as Template.
This PR fixes that:
Before this PR, Status record had codelens link, etc

Check if record implement TemplateInstance to provide the support

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/Template.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTag.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/tags/UserTagInfoCollector.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/UserTagUtils.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithIncludeSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/resources/templates/tags/tagWithArgs.html

feat: Qute: add arguments metadata for user-defined tags
Fixes #928
Here a demo with _args support (no false positive validation + completion for _args.|) //cc @ia3andy

feat: Qute: add arguments metadata for user-defined tags

---

quarkus.jdt.ext/pom.xml
qute.jdt/pom.xml

Requires https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/3271/files to be merged in jdt.ls to work properly, so we should wait to merge this.
Fixes #994

Update eclipse.jdt.ls to 1.40.0-SNAPSHOT

---

quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/OllamaConstants.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/OllamaExtension.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/OllamaItemMetadataProvider.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/OllamaItemMetadataProviderFactory.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/OllamaPropertyValidatorParticipant.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/client/OllamaClient.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/client/OllamaModel.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/extensions/ollama/client/OllamaModelsResult.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/resources/META-INF/services/org.eclipse.lsp4mp.extensions.ItemMetadataProviderFactory
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/resources/META-INF/services/org.eclipse.lsp4mp.services.properties.extensions.IPropertiesFileExtension

feat: Available Ollama models support for `quarkus.langchain4j.ollama.chat-model.model-id` property value
This PR requires https://github.com/eclipse/lsp4mp/pull/460
Those models are retrieved by consuming the Ollama API `${base-url}/v1/models` where base-url equals to:
* the value coming from declared `quarkus.langchain4j.ollama.base-url` property in the application.properties.
* http://localhost:11434 otherwise
Here the result in vscode with completion:
Here the result with validtaion:
As the error message is generic, it is not very good, LSP4MP must be improved to contribute with custom error validation message.
The Ollama models are cached, so if you add a new model in Ollama, you need to close the file and reopen it to refresh the cache (not tested but I think it should work).

feat: Available Ollama models support for quarkus.langchain4j.ollama.chat-model.model-id property value

---

qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/AbstractQuteTemplateLinkCollector.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/java/QuteJavaDiagnosticsCollector.java

[invoke "org.eclipse.jdt.core.dom.ITypeBinding.getQualifiedName()"](fix: Message: Request qute/java/documentLink failed with message: Cannot invoke "org.eclipse.jdt.core.dom.ITypeBinding.getQualifiedName()")
See https://github.com/redhat-developer/vscode-quarkus/issues/839
To test this PR::
* open https://github.com/burrsutter/ai-rubric/blob/main/src/main/java/com/burrsutter/RESTResource.java#L15
* declare an Integer field like
```
public class RESTResource {
public Integer foo;
...
}
```
In this case the Integer resolveBinding returns null.

fix: Message: Request qute/java/documentLink failed with message: Cannot invoke "org.eclipse.jdt.core.dom.ITypeBinding.getQualifiedName()"

---

quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/QuarkusLanguageIds.java
quarkus.ls.ext/com.redhat.quarkus.ls/src/main/java/com/redhat/quarkus/settings/capabilities/QuarkusRegistrationConfiguration.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/QuteLanguageIds.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/settings/capabilities/QuteCapabilityManager.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/utils/DocumentationUtils.java

fix: add languageId filter for options similar to microprofile

fix: add languageId filter for options similar to microprofile

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.site/pom.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/META-INF/MANIFEST.MF
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/META-INF/MANIFEST.MF
quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/pom.xml
quarkus.jdt.ext/pom.xml
quarkus.ls.ext/com.redhat.quarkus.ls/pom.xml
qute.jdt/com.redhat.qute.jdt.site/pom.xml
qute.jdt/com.redhat.qute.jdt.test/META-INF/MANIFEST.MF
qute.jdt/com.redhat.qute.jdt.test/pom.xml
qute.jdt/com.redhat.qute.jdt/META-INF/MANIFEST.MF
qute.jdt/com.redhat.qute.jdt/pom.xml
qute.jdt/pom.xml
qute.ls/com.redhat.qute.ls/pom.xml

chore: bump to 0.20.0

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java

False positive error with param name and user tag
Given this user tag `src/main/resources/templates/tags/user.html`
`{name}`
Given this Qute template which consume the user tag:
```
{@java.lang.String name}
{#user name}
```
name is reported as it error although it is valid.
This PR this issue.

False positive error with param name and user tag

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/BaseQuteProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/MockQuteProjectRegistry.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/DocumentPage.json
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/Paginator.json
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/RoqCollection.json
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/RoqCollections.json
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/RoqDataModel.json
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/RoqProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/Site.json
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/roq/RoqCompletionsTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/roq/RoqDiagnosticsTest.java

TemplateExtension match any support
The problem has been found by playing with roq.
If you see this code https://github.com/quarkiverse/quarkus-roq/blob/caa56a5bf839545eb58fd721b8f85d3ae3ee07fc/theme/default/src/main/resources/templates/layouts/roq-default/index.html#L14
`{#for post in site.collections.get('posts').paginated(page.paginator)}`
you can write without get
`{#for post in site.collections.posts.paginated(page.paginator)}`
It works because Roq uses matchName any https://github.com/quarkiverse/quarkus-roq/blob/caa56a5bf839545eb58fd721b8f85d3ae3ee07fc/roq-frontmatter/runtime/src/main/java/io/quarkiverse/roq/frontmatter/runtime/RoqTemplateExtension.java#L21
```
@TemplateExtension(matchName = "*", priority = QUTE_FALLBACK_PRIORITY)
public static RoqCollection …
```

TemplateExtension match any support

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus.test/pom.xml
quarkus.jdt.ext/pom.xml
qute.jdt/com.redhat.qute.jdt.test/pom.xml
qute.jdt/pom.xml

- Use the JDT-LS repository, which now contains all dependencies to build the target platform
- Include o.e.platform.feature.group for the test runtime

Improve the Target platform for JDT Extension components.

---

qute.jdt/com.redhat.qute.jdt.test/src/main/java/com/redhat/qute/jdt/template/TemplateGenerateMissingJavaMemberTest.java

We were expecting one more newline than we actually got.

Fix the qute.jdt tests

---

qute.jdt/com.redhat.qute.jdt/plugin.xml
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/DataModelProject.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/DataModelTemplate.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/datamodel/DataModelTemplateMatcher.java
qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/internal/extensions/roq/RoqDataModelProvider.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/DataModelProject.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/DataModelTemplate.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/datamodel/DataModelTemplateMatcher.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/ExtendedDataModelTemplate.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/ExtendedDataModelTemplateMatcher.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteCodeLens.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDefinition.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/roq/RoqProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/codelens/roq/RoqCodeLensTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/roq/RoqCompletionsTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/roq/RoqDiagnosticsTest.java

This PR provides the capability to inject data model parameter with pattern (instead of just template uri). This mechanims is used by roq extension to add site and page on each Qute template which are a roq application.
To test this PR,
*  open https://github.com/quarkiverse/quarkus-roq/tree/main/blog
*  create a foo.html file in https://github.com/quarkiverse/quarkus-roq/tree/main/blog/content you should see site and page as codelens:
* create a Qute expression and open completion, you should see site and page
This auto injection  of data parameter is generic. Roq extension defines a template data model like this:
```
[Trace - 11:48:52 PM] Sending response 'qute/template/projectDataModel - (17)'. Processing request took 94877ms
Result: {
"templates": [
{
"templateMatcher": {
"includes": …
```

Data model template matcher support

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/scanner/TemplateScanner.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithIncludeSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java

false positive error with section name which contains number
Open https://github.com/quarkiverse/quarkus-roq/blob/90048f75d54a8e1396245c94f39aa87950194f94/theme/default/src/main/resources/templates/partials/roq-default/head.html#L5
There is a false positive error:
It is because the fault toerant Qute parser doesn't support number in section name.
//cc @ia3andy

false positive error with section name which contains number

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/scanner/TemplateScanner.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java

Qute expression escape support.
Qute expression can be escaped with `\` and in this case we should not validate the exression like

Qute expression escape support.

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/template/scanner/TemplateScanner.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/QuteAssert.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithIncludeSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionWithUserTagTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithUserTagTest.java

false positive error with section name which contains underscore
This PR fixes false positive error when user tags contains underscore:

false positive error with section name which contains underscore

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/parser/expression/scanner/ExpressionScanner.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/parser/expression/scanner/ExpressionScannerTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java

Qute validation fails on {config:property} if property contains is a string
Fixes #933

Qute validation fails on {config:property} if property contains is a string

---

CHANGELOG.md

chore: changelog 0.21.0

---

qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/JDTTypeUtils.java

This allows for nested types to be resolved. Without a progress monitor, JDT doesn't resolve nested types.

Use progress monitor when finding types in project

---

qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/jdt/utils/JDTTypeUtils.java

Use the secondary-type search for types in the project, and if that fails, use the non-secondary type search for types.

Copy over eclipse/lsp4mp#480 into qute.jdt

---

quarkus.jdt.ext/com.redhat.microprofile.jdt.quarkus/src/main/java/com/redhat/microprofile/jdt/internal/quarkus/core/properties/QuarkusConfigMappingProvider.java

- When a type uses the ConfigMapping annotation, we populate properties for its methods. For methods with an Optional<..> return type we attempt to determine the type parameter for the Optional. This may fail so we should guard against that
Haven't been able to reproduce, but this is just something I ran into randomly.
<details>
<summary>stacktrace</summary>
```
message: Apr 10, 2025 1:37:47 P.M. org.eclipse.lsp4mp.jdt.core.AbstractAnnotationTypeReferencePropertiesProvider collectProperties
SEVERE: NativeConfig
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
at com.redhat.microprofile.jdt.internal.quarkus.core.properties.QuarkusConfigMappingProvider.populateConfigObject(QuarkusConfigMappingProvider.java:150)
at …
```

Guard against IOOBE for Optional returning method of ConfigMapped type.

---

qute.jdt/com.redhat.qute.jdt/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/commons/JavaMethodInfo.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/JavaDataModelCache.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/JavaMemberResult.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/QuteProject.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/ExtendedDataModelProject.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/project/datamodel/resolvers/MethodValueResolver.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/QuteDiagnostics.java
qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/services/completions/QuteCompletionsForExpression.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/project/QuteQuickStartProject.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/completions/QuteCompletionInInfixNotationTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithEachSectionTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInExpressionWithNamespaceTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsInNativeModeTest.java
qute.ls/com.redhat.qute.ls/src/test/java/com/redhat/qute/services/diagnostics/QuteDiagnosticsWithArraysTest.java
qute.ls/com.redhat.qute.ls/src/test/java/sandbox/TestItCountQute.java
qute.ls/com.redhat.qute.ls/src/test/java/sandbox/it_count.qute.html

Fixes https://github.com/redhat-developer/vscode-quarkus/issues/974
Here a sample which doesn't report false positive error:
```
{@int foo}
{@int[] bar}
{foo mod 10 + 58 + foo.mod(10) - 9999 minus 7}
{bar.0 + 10 - 7}
{#for item in bar}
{item + 7 + item_count - 7 minus 88}
{/for}
```
The fix is done to support correctly matchNames used in TemplateExtension.
This `+` is managed with https://github.com/quarkusio/quarkus/blob/91c8a5b95d900917039190985e9ed84e1af75eba/extensions/qute/runtime/src/main/java/io/quarkus/qute/runtime/extensions/NumberTemplateExtensions.java#L17
By fixing matchName support it allows to support features like diagnostic, completion, hover, definition, etc
Here a demo

Support for Qute Integer Numbers

---

.github/workflows/tests.yml

This lets be run in parallel. This means that we can check their failures individually, and we will probably get results sooner.
Fix #1053

Run test suites as separate jobs

---

qute.ls/com.redhat.qute.ls/src/main/java/com/redhat/qute/ls/commons/ParentProcessWatcher.java

See https://github.com/eclipse-lemminx/lemminx/pull/1753

Simplify `ParentProcessWatcher`
